export const MODULE_STATUSES = ["Active", "Inactive"] as const;

export const MODULE_PERMISSIONS = {
  VIEW_MODULE: "VIEW_MODULE",
  CREATE_MODULE: "CREATE_MODULE",
  UPDATE_MODULE: "UPDATE_MODULE",
  DELETE_MODULE: "DELETE_MODULE",
  EXPORT_MODULE: "EXPORT_MODULE",
} as const;
