import type { AttendancePrediction, StudentRisk, AnalyticsReport, AITriggerNotification } from "../types";

export const mockAttendancePredictions: AttendancePrediction[] = [
  {
    studentId: "22CS101",
    name: "K. Sai Teja",
    department: "CSE",
    currentAttendance: 84,
    predictedAttendance: 88,
    confidence: 94,
    risk: "Low",
  },
  {
    studentId: "22CS104",
    name: "Rahul Sharma",
    department: "CSE",
    currentAttendance: 71,
    predictedAttendance: 68,
    confidence: 91,
    risk: "High",
  },
  {
    studentId: "22CS108",
    name: "Aditya Vardhan",
    department: "CSE",
    currentAttendance: 78,
    predictedAttendance: 73,
    confidence: 88,
    risk: "Medium",
  },
  {
    studentId: "22EC044",
    name: "Priya Sundaram",
    department: "ECE",
    currentAttendance: 92,
    predictedAttendance: 94,
    confidence: 97,
    risk: "Low",
  },
  {
    studentId: "22EC081",
    name: "Sanjay Kumar",
    department: "ECE",
    currentAttendance: 68,
    predictedAttendance: 61,
    confidence: 85,
    risk: "Critical",
  },
  {
    studentId: "22ME089",
    name: "Anish Kulkarni",
    department: "ME",
    currentAttendance: 75,
    predictedAttendance: 79,
    confidence: 89,
    risk: "Low",
  },
  {
    studentId: "22ME092",
    name: "Vikram Rathore",
    department: "ME",
    currentAttendance: 63,
    predictedAttendance: 58,
    confidence: 90,
    risk: "Critical",
  },
  {
    studentId: "22EE012",
    name: "Divya Reddy",
    department: "EEE",
    currentAttendance: 80,
    predictedAttendance: 74,
    confidence: 87,
    risk: "Medium",
  },
  {
    studentId: "22CE005",
    name: "Harish Gupta",
    department: "Civil",
    currentAttendance: 72,
    predictedAttendance: 70,
    confidence: 86,
    risk: "High",
  },
  {
    studentId: "22CS115",
    name: "Nikhil Joshi",
    department: "CSE",
    currentAttendance: 67,
    predictedAttendance: 59,
    confidence: 92,
    risk: "Critical",
  },
];

export const mockStudentRisks: StudentRisk[] = [
  {
    studentId: "22CS104",
    name: "Rahul Sharma",
    department: "CSE",
    attendance: 71,
    internalMarks: 52,
    cgpa: 6.2,
    feeStatus: "Pending",
    riskScore: 78,
    riskLevel: "High",
    recommendation: "Assign peer tutoring and send warning notification to parent.",
  },
  {
    studentId: "22EC081",
    name: "Sanjay Kumar",
    department: "ECE",
    attendance: 68,
    internalMarks: 45,
    cgpa: 5.8,
    feeStatus: "Overdue",
    riskScore: 92,
    riskLevel: "Critical",
    recommendation: "Mandatory HOD counseling and parent-teacher meeting. Fee extension requested.",
  },
  {
    studentId: "22ME092",
    name: "Vikram Rathore",
    department: "ME",
    attendance: 63,
    internalMarks: 58,
    cgpa: 6.0,
    feeStatus: "Paid",
    riskScore: 84,
    riskLevel: "Critical",
    recommendation: "Biometric attendance tracking and remedial classes.",
  },
  {
    studentId: "22CS115",
    name: "Nikhil Joshi",
    department: "CSE",
    attendance: 67,
    internalMarks: 48,
    cgpa: 5.5,
    feeStatus: "Pending",
    riskScore: 88,
    riskLevel: "Critical",
    recommendation: "Remedial classes needed for academic threshold support.",
  },
  {
    studentId: "22CS108",
    name: "Aditya Vardhan",
    department: "CSE",
    attendance: 78,
    internalMarks: 62,
    cgpa: 6.9,
    feeStatus: "Paid",
    riskScore: 54,
    riskLevel: "Medium",
    recommendation: "Monitor attendance closely. Suggest attending study circles.",
  },
  {
    studentId: "22EE012",
    name: "Divya Reddy",
    department: "EEE",
    attendance: 80,
    internalMarks: 60,
    cgpa: 7.1,
    feeStatus: "Paid",
    riskScore: 42,
    riskLevel: "Medium",
    recommendation: "Suggest counseling to balance academics and extracurriculars.",
  },
  {
    studentId: "22CS101",
    name: "K. Sai Teja",
    department: "CSE",
    attendance: 84,
    internalMarks: 85,
    cgpa: 8.4,
    feeStatus: "Paid",
    riskScore: 12,
    riskLevel: "Low",
    recommendation: "Encourage placement registration and leadership roles.",
  },
];

export const mockReports: AnalyticsReport[] = [
  {
    id: "REP-ATT-01",
    title: "AI Attendance Shortage Forecast Report",
    category: "Attendance",
    lastGenerated: "2026-08-01 10:00 AM",
    formats: ["PDF", "Excel", "CSV"],
    size: "1.2 MB",
  },
  {
    id: "REP-RSK-02",
    title: "Student Academic Risk Analysis Ledger",
    category: "Academics",
    lastGenerated: "2026-08-01 09:30 AM",
    formats: ["PDF", "Excel"],
    size: "2.4 MB",
  },
  {
    id: "REP-PLC-03",
    title: "Batch Placement Eligibility Analytics",
    category: "Placements",
    lastGenerated: "2026-07-31 04:00 PM",
    formats: ["PDF", "CSV"],
    size: "850 KB",
  },
  {
    id: "REP-DEP-04",
    title: "Department-wise Performance Vitals",
    category: "Management",
    lastGenerated: "2026-07-30 11:15 AM",
    formats: ["PDF", "Excel", "CSV"],
    size: "3.1 MB",
  },
  {
    id: "REP-FIN-05",
    title: "Fee Collection Prediction & Revenue Forecast",
    category: "Finance",
    lastGenerated: "2026-07-29 02:00 PM",
    formats: ["PDF", "Excel"],
    size: "1.6 MB",
  },
  {
    id: "REP-HR-06",
    title: "Faculty Appraisals & Performance Indices",
    category: "HRMS",
    lastGenerated: "2026-07-28 05:30 PM",
    formats: ["PDF"],
    size: "920 KB",
  },
];

export const mockNotifications: AITriggerNotification[] = [
  {
    id: "NOT-901",
    studentId: "22EC081",
    studentName: "Sanjay Kumar",
    triggerType: "Attendance Shortage",
    channel: "All",
    recipient: "All",
    message: "Critical alert: Sanjay Kumar predicted attendance is 61%. Shortage notification sent to Parent & HOD.",
    timestamp: "2026-08-01 10:45 AM",
    status: "Sent",
  },
  {
    id: "NOT-902",
    studentId: "22CS104",
    studentName: "Rahul Sharma",
    triggerType: "Internal Performance",
    channel: "In-App",
    recipient: "Faculty",
    message: "Risk warning: Rahul Sharma internal marks dropped below 55%. Mentor notified.",
    timestamp: "2026-08-01 10:12 AM",
    status: "Sent",
  },
  {
    id: "NOT-903",
    studentId: "22CS115",
    studentName: "Nikhil Joshi",
    triggerType: "Fee Due",
    channel: "SMS",
    recipient: "Parent",
    message: "Reminder: Outstanding tuition fees for Nikhil Joshi. Please settle by end of week.",
    timestamp: "2026-08-01 09:15 AM",
    status: "Sent",
  },
  {
    id: "NOT-904",
    studentId: "22ME092",
    studentName: "Vikram Rathore",
    triggerType: "Attendance Shortage",
    channel: "Email",
    recipient: "Parent",
    message: "Urgent: Attendance predicted to drop to 58%. Remedial attendance counseling required.",
    timestamp: "2026-07-31 03:30 PM",
    status: "Sent",
  },
  {
    id: "NOT-905",
    studentId: "22CS101",
    studentName: "K. Sai Teja",
    triggerType: "Exam Registry",
    channel: "In-App",
    recipient: "Student",
    message: "Hall Ticket generated: B.Tech CSE Semester 6 End exams available for download.",
    timestamp: "2026-07-31 01:20 PM",
    status: "Sent",
  },
];
