export * from "./HostelService";
export * from "./HostelComponents";

export {
  HostelModuleView as HostelAttendanceView,
  HostelModuleView as HostelMessManagementView,
  HostelModuleView as HostelUserManagementView,
  HostelModuleView as HostelSettingsView,
  HostelModuleView as HostelGuestBillingView,
  HostelModuleView as HostelLeavesSuspensionView,
  HostelModuleView as HostelFeesView,
  HostelModuleView as HostelLogHistoryView,
  HostelModuleView as HostelMaintenanceView,
  HostelModuleView as HostelComplaintsView,
  HostelModuleView as HostelDashboardView,
  HostelModuleView as HostelRoomsView,
  HostelModuleView as HostelOccupantsView,
  HostelModuleView as HostelWardenDeskView,
  HostelModuleView as HostelGatePassesView,
  HostelModuleView as HostelInspectionAuditsView,
  HostelModuleView as HostelInventoryAssetsView,
  HostelModuleView as HostelNoticesView,
  HostelModuleView as HostelOutingLogHistoryView,
  HostelModuleView as HostelDeviceManagementView,
  HostelModuleView as HostelMessFeesView,
  HostelModuleView as HostelResidentsView,
  HostelModuleView as HostelMessMenusView,
  HostelModuleView as HostelMessInventoryView,
  HostelModuleView as HostelBedManagementView,
  HostelModuleView as HostelBlockManagementView,
  HostelModuleView as HostelRoomAllocationsView,
  HostelModuleView as HostelVisitorLogView,
  HostelModuleView as HostelStaffDutyRosterView,
  HostelModuleView as HostelVisitorsView,
  HostelModuleView as HostelBlocksView,
  HostelModuleView as HostelNotificationsView,
  HostelModuleView as HostelOutingApprovalsView,
} from "./HostelComponents";
