import {
  StudentFinanceSummary,
  FeeHeadItem,
  PaymentRecordItem,
  ReceiptItem,
  ScholarshipItem,
  RefundRequestItem,
  NoDueClearanceItem,
  InstallmentItem,
} from "./types";

export const MOCK_FINANCE_SUMMARY: StudentFinanceSummary = {
  studentId: "STU-2022-8941",
  rollNumber: "22CS101",
  studentName: "Sai Teja Varma",
  branch: "Computer Science & Engineering",
  academicYear: "2024 - 2025",
  currentSemester: 5,
  totalAcademicFee: 480000,
  amountPaid: 360000,
  pendingAmount: 45000,
  scholarshipAmount: 75000,
  concessionAmount: 15000,
  nextDueDate: "Feb 15, 2025",
  installmentsPaid: 5,
  installmentsTotal: 8,
  lateFeeCharged: 0,
  convenienceCharge: 150,
  paymentStatus: "Partially Paid",
};

export const MOCK_FEE_HEADS: FeeHeadItem[] = [
  {
    id: "FH-501",
    feeHead: "Tuition & Academic Development Fee",
    category: "Academic",
    semester: 5,
    amount: 55000,
    dueDate: "Feb 15, 2025",
    status: "Pending",
    lateFee: 0,
    description: "Core academic instruction, laboratory access and digital learning portal",
  },
  {
    id: "FH-502",
    feeHead: "Semester Examination & Evaluation Fee",
    category: "Exam",
    semester: 5,
    amount: 2500,
    dueDate: "Feb 10, 2025",
    status: "Paid",
    lateFee: 0,
    description: "End-semester examination fee and practical lab evaluation",
  },
  {
    id: "FH-503",
    feeHead: "Central Library Subscription & E-Resources",
    category: "Library",
    semester: 5,
    amount: 1500,
    dueDate: "Jan 30, 2025",
    status: "Paid",
    lateFee: 0,
    description: "IEEE Xplore, ScienceDirect digital library access and textbook lending",
  },
  {
    id: "FH-504",
    feeHead: "Campus Hostel Accommodation & Mess Charge",
    category: "Hostel",
    semester: 5,
    amount: 35000,
    dueDate: "Jan 15, 2025",
    status: "Paid",
    lateFee: 0,
    description: "Occupancy charges for Block-B Room 304 and 3 meals daily",
  },
  {
    id: "FH-505",
    feeHead: "AC Campus Bus Transport Service",
    category: "Transport",
    semester: 5,
    amount: 12000,
    dueDate: "Jan 15, 2025",
    status: "Paid",
    lateFee: 0,
    description: "Route #12 (Miyapur Express Air-Conditioned Fleet)",
  },
  {
    id: "FH-506",
    feeHead: "Placement & Skill Development Workshop",
    category: "Miscellaneous",
    semester: 5,
    amount: 4000,
    dueDate: "Feb 20, 2025",
    status: "Pending",
    lateFee: 0,
    description: "Mock technical interviews, aptitude portal and resume building",
  },
];

export const MOCK_PAYMENT_RECORDS: PaymentRecordItem[] = [
  {
    transactionId: "TXN-9082341",
    date: "Jan 14, 2025",
    amount: 35000,
    paymentMode: "Net Banking",
    referenceNumber: "HDFC982301928",
    status: "Success",
    semester: 5,
    receiptNumber: "REC-2025-0091",
    feeHead: "Hostel Accommodation",
  },
  {
    transactionId: "TXN-9081290",
    date: "Jan 12, 2025",
    amount: 12000,
    paymentMode: "UPI",
    referenceNumber: "UPI/5012391029",
    status: "Success",
    semester: 5,
    receiptNumber: "REC-2025-0088",
    feeHead: "AC Transport Service",
  },
  {
    transactionId: "TXN-9079102",
    date: "Jan 10, 2025",
    amount: 2500,
    paymentMode: "Credit Card",
    referenceNumber: "CC-AXIS-8812",
    status: "Success",
    semester: 5,
    receiptNumber: "REC-2025-0082",
    feeHead: "Exam Fee",
  },
  {
    transactionId: "TXN-8012940",
    date: "Nov 02, 2024",
    amount: 60000,
    paymentMode: "Bank Transfer",
    referenceNumber: "NEFT-SBI-10923",
    status: "Success",
    semester: 4,
    receiptNumber: "REC-2024-0512",
    feeHead: "Semester IV Academic Fee",
  },
  {
    transactionId: "TXN-7091240",
    date: "May 10, 2024",
    amount: 60000,
    paymentMode: "Net Banking",
    referenceNumber: "ICICI-88192301",
    status: "Success",
    semester: 3,
    receiptNumber: "REC-2024-0192",
    feeHead: "Semester III Academic Fee",
  },
  {
    transactionId: "TXN-6019234",
    date: "Nov 05, 2023",
    amount: 60000,
    paymentMode: "Debit Card",
    referenceNumber: "DC-HDFC-9912",
    status: "Success",
    semester: 2,
    receiptNumber: "REC-2023-0881",
    feeHead: "Semester II Academic Fee",
  },
  {
    transactionId: "TXN-5091238",
    date: "May 12, 2023",
    amount: 60000,
    paymentMode: "Net Banking",
    referenceNumber: "SBIN-9910293",
    status: "Success",
    semester: 1,
    receiptNumber: "REC-2023-0102",
    feeHead: "Semester I Tuition Fee",
  },
];

export const MOCK_RECEIPTS: ReceiptItem[] = [
  {
    receiptNumber: "REC-2025-0091",
    transactionId: "TXN-9082341",
    amount: 35000,
    paymentDate: "Jan 14, 2025",
    paymentMode: "Net Banking (HDFC Bank)",
    academicYear: "2024 - 2025",
    semester: 5,
    qrVerified: true,
  },
  {
    receiptNumber: "REC-2025-0088",
    transactionId: "TXN-9081290",
    amount: 12000,
    paymentDate: "Jan 12, 2025",
    paymentMode: "UPI (Google Pay)",
    academicYear: "2024 - 2025",
    semester: 5,
    qrVerified: true,
  },
  {
    receiptNumber: "REC-2025-0082",
    transactionId: "TXN-9079102",
    amount: 2500,
    paymentDate: "Jan 10, 2025",
    paymentMode: "Credit Card (Axis Bank)",
    academicYear: "2024 - 2025",
    semester: 5,
    qrVerified: true,
  },
  {
    receiptNumber: "REC-2024-0512",
    transactionId: "TXN-8012940",
    amount: 60000,
    paymentDate: "Nov 02, 2024",
    paymentMode: "Bank Transfer (NEFT)",
    academicYear: "2024 - 2025",
    semester: 4,
    qrVerified: true,
  },
];

export const MOCK_SCHOLARSHIPS: ScholarshipItem[] = [
  {
    id: "SCH-01",
    name: "State Merit Higher Education Scholarship",
    category: "Government Scheme",
    approvedAmount: 50000,
    status: "Approved",
    approvalStage: "Completed",
    renewalDate: "Aug 15, 2025",
    appliedDate: "Sep 10, 2024",
    disbursedAmount: 50000,
  },
  {
    id: "SCH-02",
    name: "EduSuite Academic Excellence Award",
    category: "Merit Scholarship",
    approvedAmount: 25000,
    status: "Approved",
    approvalStage: "Completed",
    renewalDate: "Sep 01, 2025",
    appliedDate: "Oct 05, 2024",
    disbursedAmount: 25000,
  },
  {
    id: "SCH-03",
    name: "National STEM Women Leadership Fellowship",
    category: "Institution Scholarship",
    approvedAmount: 30000,
    status: "Under Verification font-mono",
    approvalStage: "Finance Officer Disbursal",
    renewalDate: "Pending Verification",
    appliedDate: "Jan 15, 2025",
    disbursedAmount: 0,
  },
];

export const MOCK_REFUND_REQUESTS: RefundRequestItem[] = [
  {
    requestId: "REF-2024-091",
    amount: 5000,
    reason: "Excess Library Security Caution Deposit Adjustment",
    submittedDate: "Jan 05, 2025",
    approvalStatus: "Processed",
    processingStage: "Completed",
    expectedRefundDate: "Jan 20, 2025",
  },
  {
    requestId: "REF-2025-012",
    amount: 2000,
    reason: "Duplicate Payment for Examination Revaluation",
    submittedDate: "Jan 28, 2025",
    approvalStatus: "Under Review",
    processingStage: "Document Audit",
    expectedRefundDate: "Feb 15, 2025",
  },
];

export const MOCK_NO_DUE: NoDueClearanceItem[] = [
  { department: "Library", clearanceStatus: "Approved", clearedBy: "Chief Librarian (Mr. S. Rao)", clearedDate: "Jan 20, 2025", remarks: "All 4 borrowed textbooks returned in good condition", amountDue: 0 },
  { department: "Hostel", clearanceStatus: "Approved", clearedBy: "Hostel Warden (Prof. Ramesh)", clearedDate: "Jan 18, 2025", remarks: "Hostel mess dues cleared up to Jan 2025", amountDue: 0 },
  { department: "Transport", clearanceStatus: "Approved", clearedBy: "Transport Manager (Mr. K. Verma)", clearedDate: "Jan 15, 2025", remarks: "Transport pass active & paid", amountDue: 0 },
  { department: "Finance", clearanceStatus: "Pending", clearedBy: "Finance Officer", remarks: "Pending Sem V Tuition fee balance of Rs. 45,000", amountDue: 45000 },
  { department: "Academic / Department", clearanceStatus: "Approved", clearedBy: "HOD CSE (Dr. M. S. Anand)", clearedDate: "Jan 22, 2025", remarks: "Department lab equipment returned", amountDue: 0 },
];

export const MOCK_INSTALLMENTS: InstallmentItem[] = [
  { installmentNo: 1, dueDate: "Aug 15, 2024", amount: 60000, status: "Paid", paidDate: "Aug 10, 2024" },
  { installmentNo: 2, dueDate: "Oct 15, 2024", amount: 60000, status: "Paid", paidDate: "Oct 12, 2024" },
  { installmentNo: 3, dueDate: "Dec 15, 2024", amount: 60000, status: "Paid", paidDate: "Dec 14, 2024" },
  { installmentNo: 4, dueDate: "Feb 15, 2025", amount: 45000, status: "Upcoming" },
];

export const MOCK_CHARTS_SEM_PAYMENTS = [
  { sem: "Sem 1", paid: 60000, total: 60000 },
  { sem: "Sem 2", paid: 60000, total: 60000 },
  { sem: "Sem 3", paid: 60000, total: 60000 },
  { sem: "Sem 4", paid: 60000, total: 60000 },
  { sem: "Sem 5", paid: 49500, total: 95000 },
];

export const MOCK_CHARTS_FEE_DISTRIBUTION = [
  { name: "Tuition Fee", value: 330000, color: "#2563EB" },
  { name: "Hostel & Mess", value: 70000, color: "#10B981" },
  { name: "Transport", value: 24000, color: "#8B5CF6" },
  { name: "Exam & Misc", value: 16000, color: "#F59E0B" },
];
