import { TimetableSlot, FacultyMember, ExamScheduleItem, CalendarEventItem, NotificationItem, SummaryMetrics } from "./types";

export const mockSummaryMetrics: SummaryMetrics = {
  todaysClasses: 5,
  currentClass: "CS401 Distributed Systems • Room 302",
  nextClass: "CS404 Web Dev Lab • 11:15 AM",
  totalWeeklyClasses: 40,
  labSessions: 8,
  attendanceThisWeek: 94.2,
  freePeriods: 4,
  onlineClasses: 6,
};

export const mockFacultyList: FacultyMember[] = [
  {
    id: "f1",
    name: "Dr. Ramesh Nair",
    subject: "Distributed Systems (CS401)",
    department: "Computer Science & Engg",
    cabin: "Cabin 304, Tech Block A",
    email: "ramesh.nair@edusuite.edu",
    phone: "+91 98765 43210",
    consultationHours: "Tue & Thu: 02:00 PM – 04:00 PM",
    officeHours: "Mon – Fri: 09:00 AM – 05:00 PM",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    designation: "Professor & HOD",
  },
  {
    id: "f2",
    name: "Prof. Ananya Roy",
    subject: "AI & Machine Learning (CS402)",
    department: "Computer Science & Engg",
    cabin: "Cabin 210, Tech Block B",
    email: "ananya.roy@edusuite.edu",
    phone: "+91 98765 43211",
    consultationHours: "Mon & Wed: 11:00 AM – 01:00 PM",
    officeHours: "Mon – Fri: 09:00 AM – 05:00 PM",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    designation: "Associate Professor",
  },
  {
    id: "f3",
    name: "Dr. Vikramaditya Sen",
    subject: "Cloud Computing & DevOps (CS403)",
    department: "Information Technology",
    cabin: "Cabin 405, Innovation Hub",
    email: "vikram.sen@edusuite.edu",
    phone: "+91 98765 43212",
    consultationHours: "Friday: 03:00 PM – 05:00 PM",
    officeHours: "Mon – Fri: 09:30 AM – 05:30 PM",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    designation: "Associate Professor",
  },
  {
    id: "f4",
    name: "Prof. Sunita Sharma",
    subject: "Web Development Lab (CS404)",
    department: "Computer Science & Engg",
    cabin: "Lab 201, Software Lab Complex",
    email: "sunita.sharma@edusuite.edu",
    phone: "+91 98765 43213",
    consultationHours: "Wed: 02:00 PM – 04:00 PM",
    officeHours: "Mon – Sat: 09:00 AM – 04:30 PM",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    designation: "Assistant Professor",
  },
  {
    id: "f5",
    name: "Dr. Arvind Kulkarni",
    subject: "Database Management Systems (CS405)",
    department: "Computer Science & Engg",
    cabin: "Cabin 108, Tech Block A",
    email: "arvind.kulkarni@edusuite.edu",
    phone: "+91 98765 43214",
    consultationHours: "Mon & Thu: 10:00 AM – 12:00 PM",
    officeHours: "Mon – Fri: 09:00 AM – 05:00 PM",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    designation: "Senior Professor",
  },
  {
    id: "f6",
    name: "Prof. Kavita Reddy",
    subject: "Cyber Security & Cryptography (CS406)",
    department: "Cyber Security Dept",
    cabin: "Cabin 312, Cyber Complex",
    email: "kavita.reddy@edusuite.edu",
    phone: "+91 98765 43215",
    consultationHours: "Tue: 03:00 PM – 05:00 PM",
    officeHours: "Mon – Fri: 09:00 AM – 05:00 PM",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    designation: "Assistant Professor",
  },
  {
    id: "f7",
    name: "Dr. Rajeshwar Rao",
    subject: "Software Engineering & Agile (CS407)",
    department: "Computer Science & Engg",
    cabin: "Cabin 214, Tech Block A",
    email: "rajeshwar.rao@edusuite.edu",
    phone: "+91 98765 43216",
    consultationHours: "Thu: 02:00 PM – 04:00 PM",
    officeHours: "Mon – Fri: 09:00 AM – 05:00 PM",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    designation: "Associate Professor",
  },
  {
    id: "f8",
    name: "Prof. Priya Mehta",
    subject: "Quantum Computing Elective (CS408)",
    department: "Advanced Computing Dept",
    cabin: "Cabin 501, Research Block",
    email: "priya.mehta@edusuite.edu",
    phone: "+91 98765 43217",
    consultationHours: "Mon: 04:00 PM – 05:00 PM",
    officeHours: "Mon – Fri: 09:00 AM – 05:00 PM",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    designation: "Assistant Professor",
  },
];

export const mockWeeklyTimetableSlots: TimetableSlot[] = [
  // MONDAY
  {
    id: "m1",
    subjectCode: "CS401",
    subjectName: "Distributed Systems",
    facultyName: "Dr. Ramesh Nair",
    facultyAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "ramesh.nair@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "302",
    building: "Tech Block A",
    floor: "3rd Floor",
    dayOfWeek: "Monday",
    startTime: "09:00 AM",
    endTime: "10:00 AM",
    timeSlotKey: "09:00–10:00",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Completed",
    attendanceStatus: "Present",
    credits: 4,
    syllabusCoverage: 78,
    upcomingTopics: ["Raft Consensus Algorithm", "Vector Clocks & Logical Time", "Chandy-Lamport Snapshots"],
    assignments: ["Assignment 3: MapReduce Simulation (Due Aug 10)"],
    studyMaterial: "https://lms.edusuite.edu/cs401/lecture4.pdf",
    isOnline: false,
  },
  {
    id: "m2",
    subjectCode: "CS402",
    subjectName: "AI & Machine Learning",
    facultyName: "Prof. Ananya Roy",
    facultyAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "ananya.roy@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "405",
    building: "Tech Block B",
    floor: "4th Floor",
    dayOfWeek: "Monday",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timeSlotKey: "10:00–11:00",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Live Now",
    attendanceStatus: "Present",
    credits: 4,
    syllabusCoverage: 82,
    upcomingTopics: ["Convolutional Neural Networks", "Residual Networks (ResNet)", "Attention Mechanisms"],
    assignments: ["Lab Project 2: PyTorch Model Training"],
    studyMaterial: "https://lms.edusuite.edu/cs402/cnn-notes.pdf",
    isOnline: true,
    onlineJoinUrl: "https://meet.edusuite.edu/cs402-live",
  },
  {
    id: "m3",
    subjectCode: "CS404",
    subjectName: "Web Dev Lab & Fullstack",
    facultyName: "Prof. Sunita Sharma",
    facultyAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "sunita.sharma@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "Lab 201",
    building: "Software Lab Complex",
    floor: "2nd Floor",
    dayOfWeek: "Monday",
    startTime: "11:15 AM",
    endTime: "12:15 PM",
    timeSlotKey: "11:15–12:15",
    duration: "1 Hour",
    classType: "Lab",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 2,
    syllabusCoverage: 85,
    upcomingTopics: ["Next.js Server Components", "TanStack Router Data Loading", "PostgreSQL & Prisma Integration"],
    assignments: ["Submission 4: E-Commerce Admin Portal"],
    studyMaterial: "https://lms.edusuite.edu/cs404/lab4-guide.pdf",
    isOnline: false,
  },
  {
    id: "m4",
    subjectCode: "CS403",
    subjectName: "Cloud Computing & DevOps",
    facultyName: "Dr. Vikramaditya Sen",
    facultyAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "vikram.sen@edusuite.edu",
    department: "Information Technology",
    roomNumber: "104",
    building: "Innovation Hub",
    floor: "1st Floor",
    dayOfWeek: "Monday",
    startTime: "12:15 PM",
    endTime: "01:15 PM",
    timeSlotKey: "12:15–01:15",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 3,
    syllabusCoverage: 70,
    upcomingTopics: ["Kubernetes Pod Orchestration", "Helm Charts Setup", "Terraform Infrastructure as Code"],
    assignments: ["AWS Cloud Architecture Design Case Study"],
    studyMaterial: "https://lms.edusuite.edu/cs403/k8s-slides.pdf",
    isOnline: false,
  },
  {
    id: "m5",
    subjectCode: "CS405",
    subjectName: "Database Systems Tutorial",
    facultyName: "Dr. Arvind Kulkarni",
    facultyAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "arvind.kulkarni@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "208",
    building: "Tech Block A",
    floor: "2nd Floor",
    dayOfWeek: "Monday",
    startTime: "02:00 PM",
    endTime: "03:00 PM",
    timeSlotKey: "02:00–03:00",
    duration: "1 Hour",
    classType: "Tutorial",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 1,
    syllabusCoverage: 90,
    upcomingTopics: ["B+ Tree Indexing Problems", "ACID Isolation Levels & Locks", "Query Execution Plans"],
    assignments: ["Tutorial Worksheet 5: Query Optimization"],
    studyMaterial: "https://lms.edusuite.edu/cs405/tut5.pdf",
    isOnline: false,
  },

  // TUESDAY
  {
    id: "t1",
    subjectCode: "CS406",
    subjectName: "Cyber Security & Crypto",
    facultyName: "Prof. Kavita Reddy",
    facultyAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "kavita.reddy@edusuite.edu",
    department: "Cyber Security Dept",
    roomNumber: "312",
    building: "Cyber Complex",
    floor: "3rd Floor",
    dayOfWeek: "Tuesday",
    startTime: "09:00 AM",
    endTime: "10:00 AM",
    timeSlotKey: "09:00–10:00",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 3,
    syllabusCoverage: 75,
    upcomingTopics: ["Elliptic Curve Cryptography (ECC)", "Zero-Knowledge Proofs", "OAuth 2.0 Security Protocols"],
    assignments: ["RSA Implementation Project"],
    studyMaterial: "https://lms.edusuite.edu/cs406/crypto-ch4.pdf",
    isOnline: false,
  },
  {
    id: "t2",
    subjectCode: "CS407",
    subjectName: "Software Engineering & Agile",
    facultyName: "Dr. Rajeshwar Rao",
    facultyAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "rajeshwar.rao@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "214",
    building: "Tech Block A",
    floor: "2nd Floor",
    dayOfWeek: "Tuesday",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timeSlotKey: "10:00–11:00",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 3,
    syllabusCoverage: 80,
    upcomingTopics: ["Sprint Retrospectives", "Design Patterns: Observer & Factory", "CI/CD Pipeline Setup"],
    assignments: ["SRS Document Submission"],
    studyMaterial: "https://lms.edusuite.edu/cs407/agile-guide.pdf",
    isOnline: false,
  },
  {
    id: "t3",
    subjectCode: "CS408",
    subjectName: "Quantum Computing Elective",
    facultyName: "Prof. Priya Mehta",
    facultyAvatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "priya.mehta@edusuite.edu",
    department: "Advanced Computing Dept",
    roomNumber: "Auditorium B",
    building: "Research Block",
    floor: "5th Floor",
    dayOfWeek: "Tuesday",
    startTime: "11:15 AM",
    endTime: "12:15 PM",
    timeSlotKey: "11:15–12:15",
    duration: "1 Hour",
    classType: "Elective",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 3,
    syllabusCoverage: 65,
    upcomingTopics: ["Qubits & Superposition", "Shor's Algorithm", "Quantum Gates Matrix Representation"],
    assignments: ["Qiskit Quantum Circuit Homework"],
    studyMaterial: "https://lms.edusuite.edu/cs408/quantum-intro.pdf",
    isOnline: true,
    onlineJoinUrl: "https://meet.edusuite.edu/cs408-quantum",
  },
  {
    id: "t4",
    subjectCode: "CS401",
    subjectName: "Distributed Systems Lab",
    facultyName: "Dr. Ramesh Nair",
    facultyAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "ramesh.nair@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "Lab 305",
    building: "Software Lab Complex",
    floor: "3rd Floor",
    dayOfWeek: "Tuesday",
    startTime: "02:00 PM",
    endTime: "04:00 PM",
    timeSlotKey: "02:00–03:00",
    duration: "2 Hours",
    classType: "Lab",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 2,
    syllabusCoverage: 78,
    upcomingTopics: ["gRPC Microservices in Go", "Kafka Pub/Sub Event Streaming"],
    assignments: ["Lab Exercise 6: Distributed Key-Value Store"],
    studyMaterial: "https://lms.edusuite.edu/cs401/grpc-lab.pdf",
    isOnline: false,
  },

  // WEDNESDAY
  {
    id: "w1",
    subjectCode: "CS402",
    subjectName: "AI & Machine Learning Lab",
    facultyName: "Prof. Ananya Roy",
    facultyAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "ananya.roy@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "AI Lab 102",
    building: "Innovation Hub",
    floor: "1st Floor",
    dayOfWeek: "Wednesday",
    startTime: "09:00 AM",
    endTime: "11:00 AM",
    timeSlotKey: "09:00–10:00",
    duration: "2 Hours",
    classType: "Lab",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 2,
    syllabusCoverage: 82,
    upcomingTopics: ["TensorFlow Model Deployment", "Transfer Learning with ResNet50"],
    assignments: ["Image Classification Benchmark Notebook"],
    studyMaterial: "https://lms.edusuite.edu/cs402/tf-lab.pdf",
    isOnline: false,
  },
  {
    id: "w2",
    subjectCode: "CS405",
    subjectName: "Database Systems",
    facultyName: "Dr. Arvind Kulkarni",
    facultyAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "arvind.kulkarni@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "302",
    building: "Tech Block A",
    floor: "3rd Floor",
    dayOfWeek: "Wednesday",
    startTime: "11:15 AM",
    endTime: "12:15 PM",
    timeSlotKey: "11:15–12:15",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 4,
    syllabusCoverage: 90,
    upcomingTopics: ["NoSQL MongoDB Sharding", "PostgreSQL MVCC Concurrency"],
    assignments: ["Database Optimization Benchmark Report"],
    studyMaterial: "https://lms.edusuite.edu/cs405/nosql-slides.pdf",
    isOnline: false,
  },
  {
    id: "w3",
    subjectCode: "CS403",
    subjectName: "DevOps & CI/CD Seminar",
    facultyName: "Dr. Vikramaditya Sen",
    facultyAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "vikram.sen@edusuite.edu",
    department: "Information Technology",
    roomNumber: "Seminar Hall 1",
    building: "Tech Block B",
    floor: "Ground Floor",
    dayOfWeek: "Wednesday",
    startTime: "02:00 PM",
    endTime: "03:00 PM",
    timeSlotKey: "02:00–03:00",
    duration: "1 Hour",
    classType: "Seminar",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 1,
    syllabusCoverage: 70,
    upcomingTopics: ["GitLab CI vs GitHub Actions", "ArgoCD GitOps Deployment"],
    assignments: ["Seminar Report on GitOps Best Practices"],
    studyMaterial: "https://lms.edusuite.edu/cs403/seminar1.pdf",
    isOnline: false,
  },

  // THURSDAY
  {
    id: "th1",
    subjectCode: "CS401",
    subjectName: "Distributed Systems",
    facultyName: "Dr. Ramesh Nair",
    facultyAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "ramesh.nair@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "302",
    building: "Tech Block A",
    floor: "3rd Floor",
    dayOfWeek: "Thursday",
    startTime: "09:00 AM",
    endTime: "10:00 AM",
    timeSlotKey: "09:00–10:00",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 4,
    syllabusCoverage: 78,
    upcomingTopics: ["Byzantine Fault Tolerance", "Paxos Algorithm Deep Dive"],
    assignments: ["Read Paxos Made Simple Paper"],
    studyMaterial: "https://lms.edusuite.edu/cs401/paxos.pdf",
    isOnline: false,
  },
  {
    id: "th2",
    subjectCode: "CS406",
    subjectName: "Cyber Security Lab",
    facultyName: "Prof. Kavita Reddy",
    facultyAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "kavita.reddy@edusuite.edu",
    department: "Cyber Security Dept",
    roomNumber: "Cyber Lab 401",
    building: "Cyber Complex",
    floor: "4th Floor",
    dayOfWeek: "Thursday",
    startTime: "10:00 AM",
    endTime: "12:15 PM",
    timeSlotKey: "10:00–11:00",
    duration: "2 Hours",
    classType: "Lab",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 2,
    syllabusCoverage: 75,
    upcomingTopics: ["Penetration Testing with Wireshark & BurpSuite", "SQL Injection Prevention"],
    assignments: ["CTF Challenge 3 Writeup"],
    studyMaterial: "https://lms.edusuite.edu/cs406/ctf-guide.pdf",
    isOnline: false,
  },
  {
    id: "th3",
    subjectCode: "CS407",
    subjectName: "Software Engineering & Agile",
    facultyName: "Dr. Rajeshwar Rao",
    facultyAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "rajeshwar.rao@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "214",
    building: "Tech Block A",
    floor: "2nd Floor",
    dayOfWeek: "Thursday",
    startTime: "02:00 PM",
    endTime: "03:00 PM",
    timeSlotKey: "02:00–03:00",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 3,
    syllabusCoverage: 80,
    upcomingTopics: ["Software Architecture Metrics", "Microservices vs Monolith"],
    assignments: ["Architecture Diagram Review"],
    studyMaterial: "https://lms.edusuite.edu/cs407/arch.pdf",
    isOnline: false,
  },

  // FRIDAY
  {
    id: "f1_slot",
    subjectCode: "CS402",
    subjectName: "AI & Machine Learning",
    facultyName: "Prof. Ananya Roy",
    facultyAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "ananya.roy@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "405",
    building: "Tech Block B",
    floor: "4th Floor",
    dayOfWeek: "Friday",
    startTime: "09:00 AM",
    endTime: "10:00 AM",
    timeSlotKey: "09:00–10:00",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 4,
    syllabusCoverage: 82,
    upcomingTopics: ["Natural Language Processing", "Transformer Models & BERT"],
    assignments: ["Sentiment Analysis Project"],
    studyMaterial: "https://lms.edusuite.edu/cs402/nlp-bert.pdf",
    isOnline: true,
    onlineJoinUrl: "https://meet.edusuite.edu/cs402-nlp",
  },
  {
    id: "f2_slot",
    subjectCode: "CS403",
    subjectName: "Cloud Computing & DevOps",
    facultyName: "Dr. Vikramaditya Sen",
    facultyAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "vikram.sen@edusuite.edu",
    department: "Information Technology",
    roomNumber: "104",
    building: "Innovation Hub",
    floor: "1st Floor",
    dayOfWeek: "Friday",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timeSlotKey: "10:00–11:00",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 3,
    syllabusCoverage: 70,
    upcomingTopics: ["Serverless Lambda Functions", "DynamoDB & Cloud Security"],
    assignments: ["AWS Serverless Application Architecture"],
    studyMaterial: "https://lms.edusuite.edu/cs403/serverless.pdf",
    isOnline: false,
  },
  {
    id: "f3_slot",
    subjectCode: "CS404",
    subjectName: "Web Dev Fullstack Seminar",
    facultyName: "Prof. Sunita Sharma",
    facultyAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "sunita.sharma@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "Lab 201",
    building: "Software Lab Complex",
    floor: "2nd Floor",
    dayOfWeek: "Friday",
    startTime: "03:00 PM",
    endTime: "04:00 PM",
    timeSlotKey: "03:00–04:00",
    duration: "1 Hour",
    classType: "Seminar",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 1,
    syllabusCoverage: 85,
    upcomingTopics: ["PWA Progressive Web Apps", "WebSockets Realtime Sync"],
    assignments: ["PWA Demo App"],
    studyMaterial: "https://lms.edusuite.edu/cs404/pwa.pdf",
    isOnline: false,
  },

  // SATURDAY
  {
    id: "s1",
    subjectCode: "CS408",
    subjectName: "Quantum Computing Lab",
    facultyName: "Prof. Priya Mehta",
    facultyAvatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "priya.mehta@edusuite.edu",
    department: "Advanced Computing Dept",
    roomNumber: "Research Lab 5",
    building: "Research Block",
    floor: "5th Floor",
    dayOfWeek: "Saturday",
    startTime: "09:00 AM",
    endTime: "11:00 AM",
    timeSlotKey: "09:00–10:00",
    duration: "2 Hours",
    classType: "Lab",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 2,
    syllabusCoverage: 65,
    upcomingTopics: ["IBM Quantum Hardware Execution", "Quantum Teleportation Code"],
    assignments: ["IBM Q Experience Execution Results"],
    studyMaterial: "https://lms.edusuite.edu/cs408/ibmq.pdf",
    isOnline: true,
    onlineJoinUrl: "https://meet.edusuite.edu/cs408-lab",
  },
  {
    id: "s2",
    subjectCode: "CS405",
    subjectName: "Database Systems",
    facultyName: "Dr. Arvind Kulkarni",
    facultyAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    facultyEmail: "arvind.kulkarni@edusuite.edu",
    department: "Computer Science & Engg",
    roomNumber: "302",
    building: "Tech Block A",
    floor: "3rd Floor",
    dayOfWeek: "Saturday",
    startTime: "11:15 AM",
    endTime: "12:15 PM",
    timeSlotKey: "11:15–12:15",
    duration: "1 Hour",
    classType: "Lecture",
    status: "Upcoming",
    attendanceStatus: "Scheduled",
    credits: 4,
    syllabusCoverage: 90,
    upcomingTopics: ["Graph Databases & Neo4j", "Distributed Query Processing"],
    assignments: ["Graph DB Query Submission"],
    studyMaterial: "https://lms.edusuite.edu/cs405/neo4j.pdf",
    isOnline: false,
  },
];

export const mockExamSchedule: ExamScheduleItem[] = [
  {
    id: "e1",
    examName: "Mid-Term Examination II",
    subjectCode: "CS401",
    subjectName: "Distributed Systems",
    date: "August 18, 2026",
    time: "10:00 AM – 12:00 PM",
    venue: "Main Examination Hall A",
    seatNumber: "A-142",
    hallTicketStatus: "Issued",
    duration: "2 Hours",
    maxMarks: 50,
  },
  {
    id: "e2",
    examName: "Mid-Term Examination II",
    subjectCode: "CS402",
    subjectName: "AI & Machine Learning",
    date: "August 20, 2026",
    time: "10:00 AM – 12:00 PM",
    venue: "Main Examination Hall B",
    seatNumber: "B-088",
    hallTicketStatus: "Issued",
    duration: "2 Hours",
    maxMarks: 50,
  },
  {
    id: "e3",
    examName: "Mid-Term Examination II",
    subjectCode: "CS403",
    subjectName: "Cloud Computing & DevOps",
    date: "August 22, 2026",
    time: "02:00 PM – 04:00 PM",
    venue: "Tech Block Complex Auditorium",
    seatNumber: "AUD-210",
    hallTicketStatus: "Generated",
    duration: "2 Hours",
    maxMarks: 50,
  },
  {
    id: "e4",
    examName: "Practical Lab Examination",
    subjectCode: "CS404",
    subjectName: "Web Development Lab",
    date: "August 25, 2026",
    time: "09:00 AM – 12:00 PM",
    venue: "Software Lab 201",
    seatNumber: "LAB-12",
    hallTicketStatus: "Issued",
    duration: "3 Hours",
    maxMarks: 100,
  },
];

export const mockCalendarEvents: CalendarEventItem[] = [
  {
    id: "c1",
    date: "2026-08-01",
    title: "CS401 Distributed Systems Lecture & Quiz",
    type: "Class",
    description: "Regular morning lecture followed by a 15 min MCQ quick quiz.",
    timeSlot: "09:00 AM - 10:00 AM",
    location: "Room 302, Tech Block A",
  },
  {
    id: "c2",
    date: "2026-08-01",
    title: "CS404 Web Dev Practical Session",
    type: "Lab",
    description: "Fullstack Next.js and Prisma database connection evaluation.",
    timeSlot: "11:15 AM - 12:15 PM",
    location: "Software Lab 201",
  },
  {
    id: "c3",
    date: "2026-08-05",
    title: "Guest Lecture: Generative AI in Production",
    type: "Event",
    description: "Industry expert talk by Senior Engineer from Google Research.",
    timeSlot: "02:00 PM - 04:00 PM",
    location: "Main Campus Auditorium",
  },
  {
    id: "c4",
    date: "2026-08-15",
    title: "Independence Day Holiday",
    type: "Holiday",
    description: "National Holiday. Campus closed.",
  },
  {
    id: "c5",
    date: "2026-08-18",
    title: "CS401 Mid-Term Examination",
    type: "Exam",
    description: "Mid-Term II offline written examination for Distributed Systems.",
    timeSlot: "10:00 AM - 12:00 PM",
    location: "Hall A, Seat A-142",
  },
  {
    id: "c6",
    date: "2026-08-20",
    title: "CS402 AI & Machine Learning Exam",
    type: "Exam",
    description: "Mid-Term II examination covering Neural Networks & ResNet.",
    timeSlot: "10:00 AM - 12:00 PM",
    location: "Hall B, Seat B-088",
  },
  {
    id: "c7",
    date: "2026-08-28",
    title: "Approved Academic Leave",
    type: "Leave",
    description: "Approved leave for attending Inter-College Hackathon.",
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: "n1",
    title: "Room Change for CS402 Today",
    time: "10 mins ago",
    type: "alert",
    description: "AI & ML class at 10:00 AM has been relocated to Online Virtual Room.",
  },
  {
    id: "n2",
    title: "CS401 Assignment 3 Released",
    time: "1 hour ago",
    type: "info",
    description: "MapReduce simulation problem statement posted on EduSuite LMS.",
  },
  {
    id: "n3",
    title: "Mid-Term II Hall Ticket Available",
    time: "3 hours ago",
    type: "exam",
    description: "Your digital hall ticket for Mid-Term II exams has been generated.",
  },
  {
    id: "n4",
    title: "Upcoming Holiday: Aug 15",
    time: "Yesterday",
    type: "holiday",
    description: "Campus will remain closed for Independence Day celebrations.",
  },
];
