import {
  StudentAttendanceProfile,
  SubjectAttendanceItem,
  TodayScheduleItem,
  AttendanceHistoryRecord,
  CalendarDayItem,
  LeaveRequestItem,
  LeaveBalanceSummary,
  AcademicYearOption,
} from "./types";

export const MOCK_STUDENT_ATTENDANCE_PROFILE: StudentAttendanceProfile = {
  studentId: "STU-2024-0542",
  rollNumber: "22071A0542",
  name: "Gudipati Chandra",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  program: "B.Tech",
  branch: "Computer Science & Engineering",
  section: "CSE-A",
  academicYear: "3rd Year",
  semester: 5,
  overallAttendancePct: 86.5,
  todayAttendanceStatus: "Present",
  presentClasses: 132,
  absentClasses: 14,
  leaveClasses: 6,
  condonationStatus: "Eligible",
  currentStreak: 18,
  classesRequiredFor75: 0,
  classesRequiredFor85: 0,
  lowAttendanceCount: 1,
};

export const MOCK_TODAY_SCHEDULE: TodayScheduleItem[] = [
  {
    id: "p1",
    period: "Period 1",
    timing: "09:30 AM - 10:30 AM",
    subjectCode: "CS301",
    subjectName: "Computer Networks",
    facultyName: "Dr. A. K. Sharma",
    room: "Block A - 301",
    status: "Present",
    mode: "Biometric",
  },
  {
    id: "p2",
    period: "Period 2",
    timing: "10:30 AM - 11:30 AM",
    subjectCode: "CS302",
    subjectName: "Database Management Systems",
    facultyName: "Prof. S. R. Rao",
    room: "Block A - 301",
    status: "Present",
    mode: "Biometric",
  },
  {
    id: "p3",
    period: "Period 3",
    timing: "11:30 AM - 12:30 PM",
    subjectCode: "CS306",
    subjectName: "Design & Analysis of Algorithms",
    facultyName: "Dr. G. Ramesh",
    room: "Block A - 302",
    status: "Present",
    mode: "QR Code",
  },
  {
    id: "p4",
    period: "Period 4",
    timing: "01:30 PM - 02:30 PM",
    subjectCode: "OE311",
    subjectName: "Intellectual Property Rights",
    facultyName: "Dr. V. N. Swamy",
    room: "Block B - 204",
    status: "Pending",
    mode: "Manual",
  },
];

// Subjects per semester map
export const MOCK_ALL_SUBJECTS: SubjectAttendanceItem[] = [
  // SEMESTER 5 SUBJECTS (3rd Year)
  {
    id: "sub-501",
    academicYear: "3rd Year",
    semester: 5,
    subjectCode: "CS301",
    subjectName: "Computer Networks",
    facultyName: "Dr. A. K. Sharma",
    facultyDesignation: "Professor & Head",
    facultyEmail: "ak.sharma@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 48,
    attended: 44,
    absent: 3,
    leave: 1,
    attendancePct: 91.6,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 3,
    medicalLeaves: 1,
    facultyRemarks: "Excellent lab participation & TCP/IP assignments completed.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [
      { month: "Sep", pct: 90.0 },
      { month: "Oct", pct: 93.5 },
      { month: "Nov", pct: 91.0 },
      { month: "Dec", pct: 92.0 },
    ],
    weeklyTrend: [
      { week: "W1", pct: 90.0 },
      { week: "W2", pct: 95.0 },
      { week: "W3", pct: 88.0 },
      { week: "W4", pct: 93.0 },
    ],
    historyLogs: [],
  },
  {
    id: "sub-502",
    academicYear: "3rd Year",
    semester: 5,
    subjectCode: "CS302",
    subjectName: "Database Management Systems",
    facultyName: "Prof. S. R. Rao",
    facultyDesignation: "Associate Professor",
    facultyEmail: "sr.rao@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 52,
    attended: 46,
    absent: 4,
    leave: 2,
    attendancePct: 88.5,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 4,
    medicalLeaves: 1,
    facultyRemarks: "Good query submission rate. Maintain momentum.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [
      { month: "Sep", pct: 86.0 },
      { month: "Oct", pct: 90.0 },
      { month: "Nov", pct: 88.0 },
      { month: "Dec", pct: 89.0 },
    ],
    weeklyTrend: [
      { week: "W1", pct: 85.0 },
      { week: "W2", pct: 90.0 },
      { week: "W3", pct: 88.0 },
      { week: "W4", pct: 91.0 },
    ],
    historyLogs: [],
  },
  {
    id: "sub-503",
    academicYear: "3rd Year",
    semester: 5,
    subjectCode: "OE311",
    subjectName: "Intellectual Property Rights",
    facultyName: "Dr. V. N. Swamy",
    facultyDesignation: "Adjunct Professor",
    facultyEmail: "vn.swamy@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    credits: 3.0,
    conducted: 38,
    attended: 28,
    absent: 8,
    leave: 2,
    attendancePct: 73.7,
    status: "Below 75%",
    classesNeeded75: 2,
    classesNeeded85: 7,
    classesMissed: 8,
    medicalLeaves: 2,
    facultyRemarks: "SHORTAGE WARNING: Attend next 2 consecutive classes.",
    aiRiskPrediction: "High Shortage Risk",
    monthlyTrend: [
      { month: "Sep", pct: 75.0 },
      { month: "Oct", pct: 72.0 },
      { month: "Nov", pct: 74.0 },
      { month: "Dec", pct: 73.7 },
    ],
    weeklyTrend: [
      { week: "W1", pct: 70.0 },
      { week: "W2", pct: 74.0 },
      { week: "W3", pct: 72.0 },
      { week: "W4", pct: 78.0 },
    ],
    historyLogs: [],
  },
  {
    id: "sub-504",
    academicYear: "3rd Year",
    semester: 5,
    subjectCode: "CS305",
    subjectName: "Software Engineering & Agile",
    facultyName: "Mr. M. Praveen",
    facultyDesignation: "Assistant Professor",
    facultyEmail: "m.praveen@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80",
    credits: 3.0,
    conducted: 40,
    attended: 35,
    absent: 3,
    leave: 2,
    attendancePct: 87.5,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 3,
    medicalLeaves: 1,
    facultyRemarks: "Good active contribution in sprint planning exercises.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [
      { month: "Sep", pct: 85.0 },
      { month: "Oct", pct: 88.0 },
      { month: "Nov", pct: 87.0 },
      { month: "Dec", pct: 89.0 },
    ],
    weeklyTrend: [
      { week: "W1", pct: 85.0 },
      { week: "W2", pct: 87.0 },
      { week: "W3", pct: 89.0 },
      { week: "W4", pct: 88.0 },
    ],
    historyLogs: [],
  },

  // SEMESTER 6 SUBJECTS (3rd Year)
  {
    id: "sub-601",
    academicYear: "3rd Year",
    semester: 6,
    subjectCode: "CS308",
    subjectName: "Machine Learning & Neural Networks",
    facultyName: "Dr. S. K. Roy",
    facultyDesignation: "Professor",
    facultyEmail: "sk.roy@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 45,
    attended: 41,
    absent: 3,
    leave: 1,
    attendancePct: 91.1,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 3,
    medicalLeaves: 0,
    facultyRemarks: "Regularly submits PyTorch lab exercises.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [
      { month: "Jan", pct: 90.0 },
      { month: "Feb", pct: 92.0 },
    ],
    weeklyTrend: [
      { week: "W1", pct: 90.0 },
      { week: "W2", pct: 92.0 },
    ],
    historyLogs: [],
  },

  // SEMESTER 1 SUBJECTS (1st Year)
  {
    id: "sub-101",
    academicYear: "1st Year",
    semester: 1,
    subjectCode: "MA101",
    subjectName: "Linear Algebra & Calculus",
    facultyName: "Dr. P. Sharma",
    facultyDesignation: "Professor",
    facultyEmail: "p.sharma@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 50,
    attended: 46,
    absent: 3,
    leave: 1,
    attendancePct: 92.0,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 3,
    medicalLeaves: 0,
    facultyRemarks: "Completed semester with distinction attendance.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Aug", pct: 92.0 }],
    weeklyTrend: [{ week: "W1", pct: 92.0 }],
    historyLogs: [],
  },
  {
    id: "sub-102",
    academicYear: "1st Year",
    semester: 1,
    subjectCode: "PH102",
    subjectName: "Engineering Physics",
    facultyName: "Dr. R. K. Varma",
    facultyDesignation: "Associate Professor",
    facultyEmail: "rk.varma@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 45,
    attended: 40,
    absent: 4,
    leave: 1,
    attendancePct: 88.9,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 4,
    medicalLeaves: 1,
    facultyRemarks: "Good optics lab attendance.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Aug", pct: 88.9 }],
    weeklyTrend: [{ week: "W1", pct: 88.9 }],
    historyLogs: [],
  },

  // SEMESTER 2 SUBJECTS (1st Year)
  {
    id: "sub-201",
    academicYear: "1st Year",
    semester: 2,
    subjectCode: "MA105",
    subjectName: "Differential Equations & Vector Calculus",
    facultyName: "Dr. P. Sharma",
    facultyDesignation: "Professor",
    facultyEmail: "p.sharma@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 48,
    attended: 43,
    absent: 4,
    leave: 1,
    attendancePct: 89.5,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 4,
    medicalLeaves: 0,
    facultyRemarks: "Consistent class participation.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Jan", pct: 89.5 }],
    weeklyTrend: [{ week: "W1", pct: 89.5 }],
    historyLogs: [],
  },
  {
    id: "sub-202",
    academicYear: "1st Year",
    semester: 2,
    subjectCode: "CS107",
    subjectName: "Data Structures & Algorithms",
    facultyName: "Prof. S. R. Rao",
    facultyDesignation: "Associate Professor",
    facultyEmail: "sr.rao@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 50,
    attended: 47,
    absent: 2,
    leave: 1,
    attendancePct: 94.0,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 2,
    medicalLeaves: 0,
    facultyRemarks: "Top performer in coding labs.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Feb", pct: 94.0 }],
    weeklyTrend: [{ week: "W1", pct: 94.0 }],
    historyLogs: [],
  },

  // SEMESTER 3 SUBJECTS (2nd Year)
  {
    id: "sub-301",
    academicYear: "2nd Year",
    semester: 3,
    subjectCode: "CS201",
    subjectName: "Mathematical Foundations of CS",
    facultyName: "Dr. G. Ramesh",
    facultyDesignation: "Associate Professor",
    facultyEmail: "g.ramesh@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 44,
    attended: 37,
    absent: 5,
    leave: 2,
    attendancePct: 84.0,
    status: "75% - 85%",
    classesNeeded75: 0,
    classesNeeded85: 1,
    classesMissed: 5,
    medicalLeaves: 1,
    facultyRemarks: "Needs to maintain minimum 85% benchmark.",
    aiRiskPrediction: "Moderate Risk",
    monthlyTrend: [{ month: "Sep", pct: 84.0 }],
    weeklyTrend: [{ week: "W1", pct: 84.0 }],
    historyLogs: [],
  },
  {
    id: "sub-302",
    academicYear: "2nd Year",
    semester: 3,
    subjectCode: "CS203",
    subjectName: "Object Oriented Programming through Java",
    facultyName: "Mr. M. Praveen",
    facultyDesignation: "Assistant Professor",
    facultyEmail: "m.praveen@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 52,
    attended: 48,
    absent: 3,
    leave: 1,
    attendancePct: 92.3,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 3,
    medicalLeaves: 0,
    facultyRemarks: "Active in Java GUI lab projects.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Oct", pct: 92.3 }],
    weeklyTrend: [{ week: "W1", pct: 92.3 }],
    historyLogs: [],
  },

  // SEMESTER 4 SUBJECTS (2nd Year)
  {
    id: "sub-401",
    academicYear: "2nd Year",
    semester: 4,
    subjectCode: "CS205",
    subjectName: "Formal Languages & Automata Theory",
    facultyName: "Dr. S. K. Roy",
    facultyDesignation: "Professor",
    facultyEmail: "sk.roy@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 46,
    attended: 37,
    absent: 7,
    leave: 2,
    attendancePct: 80.4,
    status: "75% - 85%",
    classesNeeded75: 0,
    classesNeeded85: 3,
    classesMissed: 7,
    medicalLeaves: 1,
    facultyRemarks: "Regular attendance recommended for DFA/NFA concepts.",
    aiRiskPrediction: "Moderate Risk",
    monthlyTrend: [{ month: "Jan", pct: 80.4 }],
    weeklyTrend: [{ week: "W1", pct: 80.4 }],
    historyLogs: [],
  },
  {
    id: "sub-402",
    academicYear: "2nd Year",
    semester: 4,
    subjectCode: "CS206",
    subjectName: "Operating Systems & Systems Programming",
    facultyName: "Dr. Ramesh Nair",
    facultyDesignation: "Professor & HOD",
    facultyEmail: "ramesh.nair@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 48,
    attended: 42,
    absent: 4,
    leave: 2,
    attendancePct: 87.5,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 4,
    medicalLeaves: 1,
    facultyRemarks: "Good Linux kernel lab submissions.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Feb", pct: 87.5 }],
    weeklyTrend: [{ week: "W1", pct: 87.5 }],
    historyLogs: [],
  },
  {
    id: "sub-403",
    academicYear: "2nd Year",
    semester: 4,
    subjectCode: "CS208",
    subjectName: "Python Application Development",
    facultyName: "Prof. Ananya Sharma",
    facultyDesignation: "Associate Professor",
    facultyEmail: "ananya.sharma@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    credits: 3.0,
    conducted: 40,
    attended: 37,
    absent: 2,
    leave: 1,
    attendancePct: 92.5,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 2,
    medicalLeaves: 0,
    facultyRemarks: "Outstanding Django web project.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Mar", pct: 92.5 }],
    weeklyTrend: [{ week: "W1", pct: 92.5 }],
    historyLogs: [],
  },
  {
    id: "sub-404",
    academicYear: "2nd Year",
    semester: 4,
    subjectCode: "HS209",
    subjectName: "Managerial Economics & Financial Analysis",
    facultyName: "Dr. V. N. Swamy",
    facultyDesignation: "Adjunct Professor",
    facultyEmail: "vn.swamy@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    credits: 3.0,
    conducted: 36,
    attended: 27,
    absent: 7,
    leave: 2,
    attendancePct: 75.0,
    status: "Below 75%",
    classesNeeded75: 0,
    classesNeeded85: 5,
    classesMissed: 7,
    medicalLeaves: 1,
    facultyRemarks: "ATTENDANCE CRITICAL: Exactly at 75% boundary.",
    aiRiskPrediction: "High Shortage Risk",
    monthlyTrend: [{ month: "Apr", pct: 75.0 }],
    weeklyTrend: [{ week: "W1", pct: 75.0 }],
    historyLogs: [],
  },

  // SEMESTER 7 SUBJECTS (4th Year)
  {
    id: "sub-701",
    academicYear: "4th Year",
    semester: 7,
    subjectCode: "CS401",
    subjectName: "Distributed Systems & Cloud Computing",
    facultyName: "Dr. Ramesh Nair",
    facultyDesignation: "Professor & HOD",
    facultyEmail: "ramesh.nair@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 42,
    attended: 39,
    absent: 2,
    leave: 1,
    attendancePct: 92.8,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 2,
    medicalLeaves: 0,
    facultyRemarks: "Strong understanding of Raft consensus protocol.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Aug", pct: 92.8 }],
    weeklyTrend: [{ week: "W1", pct: 92.8 }],
    historyLogs: [],
  },
  {
    id: "sub-702",
    academicYear: "4th Year",
    semester: 7,
    subjectCode: "CS403",
    subjectName: "Big Data Analytics & Hadoop",
    facultyName: "Dr. K. V. Rao",
    facultyDesignation: "Professor",
    facultyEmail: "kv.rao@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    credits: 4.0,
    conducted: 40,
    attended: 37,
    absent: 2,
    leave: 1,
    attendancePct: 92.5,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 2,
    medicalLeaves: 0,
    facultyRemarks: "Excellent MapReduce cluster simulation.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Sep", pct: 92.5 }],
    weeklyTrend: [{ week: "W1", pct: 92.5 }],
    historyLogs: [],
  },

  // SEMESTER 8 SUBJECTS (4th Year)
  {
    id: "sub-801",
    academicYear: "4th Year",
    semester: 8,
    subjectCode: "CS406",
    subjectName: "Major Project Work & Viva Voce",
    facultyName: "Dr. Ramesh Nair",
    facultyDesignation: "Professor & HOD",
    facultyEmail: "ramesh.nair@edusuite.edu",
    facultyAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    credits: 10.0,
    conducted: 60,
    attended: 58,
    absent: 1,
    leave: 1,
    attendancePct: 96.6,
    status: "Above 85%",
    classesNeeded75: 0,
    classesNeeded85: 0,
    classesMissed: 1,
    medicalLeaves: 0,
    facultyRemarks: "Outstanding project implementation & final presentation.",
    aiRiskPrediction: "Low Risk",
    monthlyTrend: [{ month: "Jan", pct: 96.6 }],
    weeklyTrend: [{ week: "W1", pct: 96.6 }],
    historyLogs: [],
  },
];

export const MOCK_ATTENDANCE_HISTORY: AttendanceHistoryRecord[] = [
  {
    id: "h-101",
    date: "Jan 18, 2025",
    day: "Saturday",
    period: "Period 1",
    timeSlot: "09:30 AM - 10:30 AM",
    subjectCode: "CS301",
    subjectName: "Computer Networks",
    facultyName: "Dr. A. K. Sharma",
    room: "Block A - 301",
    status: "Present",
    mode: "Biometric",
    remarks: "Biometric punch verified at Block A #02",
  },
  {
    id: "h-102",
    date: "Jan 18, 2025",
    day: "Saturday",
    period: "Period 2",
    timeSlot: "10:30 AM - 11:30 AM",
    subjectCode: "CS302",
    subjectName: "Database Management Systems",
    facultyName: "Prof. S. R. Rao",
    room: "Block A - 301",
    status: "Present",
    mode: "Biometric",
    remarks: "Biometric punch verified",
  },
  {
    id: "h-103",
    date: "Jan 17, 2025",
    day: "Friday",
    period: "Period 4",
    timeSlot: "01:30 PM - 02:30 PM",
    subjectCode: "OE311",
    subjectName: "Intellectual Property Rights",
    facultyName: "Dr. V. N. Swamy",
    room: "Block B - 204",
    status: "Absent",
    mode: "Manual",
    remarks: "Marked absent during classroom roll call",
  },
  {
    id: "h-104",
    date: "Jan 15, 2025",
    day: "Wednesday",
    period: "Period 1",
    timeSlot: "09:30 AM - 10:30 AM",
    subjectCode: "CS301",
    subjectName: "Computer Networks",
    facultyName: "Dr. A. K. Sharma",
    room: "Block A - 301",
    status: "Medical Leave",
    mode: "Manual",
    remarks: "Sanctioned Medical Leave (ML-2025-089)",
  },
  {
    id: "h-105",
    date: "Jan 14, 2025",
    day: "Tuesday",
    period: "Period 5-7",
    timeSlot: "02:30 PM - 05:00 PM",
    subjectCode: "CS305",
    subjectName: "Software Engineering & Agile",
    facultyName: "Mr. M. Praveen",
    room: "Lab Block - 04",
    status: "On Duty",
    mode: "Manual",
    remarks: "Smart India Hackathon Finals (OD Approved)",
  },
];

export const MOCK_CALENDAR_ITEMS: CalendarDayItem[] = Array.from({ length: 31 }, (_, i) => {
  const dayNum = i + 1;
  const isWeekend = [4, 5, 11, 12, 18, 19, 25, 26].includes(dayNum);
  const isHoliday = dayNum === 14 || dayNum === 15;
  const isAbsentDay = dayNum === 9 || dayNum === 16;
  const isLeaveDay = dayNum === 8;

  let status: "Present" | "Absent" | "Leave" | "Holiday" | "Exam" = "Present";
  if (isHoliday) status = "Holiday";
  else if (isWeekend) status = "Holiday";
  else if (isAbsentDay) status = "Absent";
  else if (isLeaveDay) status = "Leave";

  return {
    date: `2025-01-${dayNum < 10 ? "0" + dayNum : dayNum}`,
    dayNumber: dayNum,
    dayName: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][(dayNum + 2) % 7],
    status,
    title: isHoliday ? (dayNum === 14 ? "Makar Sankranti" : "Pongal Holiday") : undefined,
    periods: isWeekend || isHoliday ? [] : MOCK_TODAY_SCHEDULE,
  };
});

export const MOCK_LEAVE_BALANCE: LeaveBalanceSummary = {
  availableLeaves: 6,
  appliedLeaves: 8,
  approved: 5,
  pending: 1,
  rejected: 2,
  medical: 3,
  emergency: 1,
  onDuty: 4,
};

export const MOCK_LEAVE_REQUESTS: LeaveRequestItem[] = [
  {
    id: "LV-2025-014",
    leaveType: "Medical Leave",
    reason: "High viral fever. Doctor recommended 1 day rest.",
    appliedDate: "Jan 14, 2025",
    fromDate: "Jan 15, 2025",
    toDate: "Jan 15, 2025",
    days: 1,
    status: "Approved",
    approvedBy: "Dr. A. K. Sharma (HOD)",
    remarks: "Medical certificate verified & ML granted.",
    documentName: "Medical_Cert_Jan15.pdf",
    emergencyContact: "+91 9876543210",
  },
  {
    id: "LV-2025-021",
    leaveType: "On Duty (OD)",
    reason: "Smart India Hackathon Finals participation at IIT.",
    appliedDate: "Jan 13, 2025",
    fromDate: "Jan 14, 2025",
    toDate: "Jan 14, 2025",
    days: 1,
    status: "Approved",
    approvedBy: "Prof. S. R. Rao",
    remarks: "Represented college team. OD granted.",
    documentName: "Hackathon_Invitation.pdf",
    emergencyContact: "+91 9876543210",
  },
  {
    id: "LV-2025-033",
    leaveType: "Casual Leave",
    reason: "Attending cousin wedding ceremony.",
    appliedDate: "Jan 20, 2025",
    fromDate: "Jan 24, 2025",
    toDate: "Jan 24, 2025",
    days: 1,
    status: "Pending",
    approvedBy: "Awaiting Advisor Review",
    remarks: "Under review by Faculty Advisor",
    emergencyContact: "+91 9876543210",
  },
];
