import {
  StudentInfo,
  ScheduleItem,
  TaskItem,
  EventItem,
  AttendanceSnapshot,
  ExamSnapshot,
  FinanceSnapshot,
  LmsSnapshot,
  LibrarySnapshot,
  HostelSnapshot,
  TransportSnapshot,
  PlacementSnapshot,
  AnnouncementItem,
  RecentActivityItem,
} from "./types";

export const MOCK_STUDENT_INFO: StudentInfo = {
  name: "Aditya Verma",
  rollNumber: "2021CSE084",
  registrationNumber: "REG/2021/84920",
  program: "B.Tech",
  department: "Computer Science & Engineering",
  academicYear: "2024 - 2025",
  currentSemester: 7,
  batch: "2021 - 2025",
  status: "Active",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
  lastLogin: "Today at 09:14 AM (IP: 192.168.1.45)",
  email: "aditya.v@edusuite.edu.in",
  classAdvisor: "Dr. K. S. Ramanujam",
  advisorContact: "+91 98450 12345",
};

export const MOCK_SCHEDULE: ScheduleItem[] = [
  {
    id: "sc-1",
    subjectCode: "CS401",
    subjectName: "Distributed Systems",
    faculty: "Dr. Ramesh Nair",
    room: "302",
    building: "Academic Block A",
    startTime: "09:00 AM",
    endTime: "10:00 AM",
    status: "Completed",
    attendanceStatus: "Present",
    isOnline: false,
  },
  {
    id: "sc-2",
    subjectCode: "CS402",
    subjectName: "Cryptography & Net Security",
    faculty: "Prof. Sarah Paul",
    room: "Lab 4",
    building: "IT Centre",
    startTime: "10:15 AM",
    endTime: "11:45 AM",
    status: "Current",
    attendanceStatus: "Present",
    isOnline: true,
    joinUrl: "https://meet.edusuite.pro/cs402-crypto",
  },
  {
    id: "sc-3",
    subjectCode: "CS403",
    subjectName: "Theory of Computation",
    faculty: "Dr. Ravi Shankar",
    room: "204",
    building: "Academic Block B",
    startTime: "12:00 PM",
    endTime: "01:00 PM",
    status: "Next",
    attendanceStatus: "Pending",
    isOnline: false,
  },
  {
    id: "sc-4",
    subjectCode: "CS404",
    subjectName: "Digital Logic Design Lab",
    faculty: "Mrs. Priya Sen",
    room: "Hardware Lab 1",
    building: "Academic Block A",
    startTime: "02:00 PM",
    endTime: "04:00 PM",
    status: "Upcoming",
    attendanceStatus: "Pending",
    isOnline: false,
  },
];

export const MOCK_TASKS: TaskItem[] = [
  {
    id: "task-1",
    title: "Distributed Systems RPC Lab Report Submission",
    category: "Assignment",
    dueDate: "Aug 04, 2026",
    priority: "High",
    status: "Pending",
    route: "/student/lms",
  },
  {
    id: "task-2",
    title: "Cryptography AES Encryption Quiz",
    category: "Quiz",
    dueDate: "Aug 05, 2026",
    priority: "High",
    status: "Pending",
    route: "/student/lms",
  },
  {
    id: "task-3",
    title: "Digital Logic FPGA Simulation Verification",
    category: "Lab",
    dueDate: "Aug 06, 2026",
    priority: "Medium",
    status: "In Progress",
    route: "/student/lms",
  },
  {
    id: "task-4",
    title: "Semester VII Examination Fee Clearance",
    category: "Fee",
    dueDate: "Aug 10, 2026",
    priority: "Medium",
    status: "Action Required",
    route: "/student/finance",
  },
  {
    id: "task-5",
    title: "Return 'Clean Code' to Main Library",
    category: "Library",
    dueDate: "Aug 12, 2026",
    priority: "Low",
    status: "Pending",
    route: "/student/library",
  },
  {
    id: "task-6",
    title: "End-Semester Examination Subject Registration",
    category: "Exam Reg",
    dueDate: "Aug 07, 2026",
    priority: "High",
    status: "Pending",
    route: "/student/examinations",
  },
  {
    id: "task-7",
    title: "Elective Course Final Confirmation",
    category: "Course Reg",
    dueDate: "Aug 09, 2026",
    priority: "Medium",
    status: "In Progress",
    route: "/student/lms",
  },
  {
    id: "task-8",
    title: "Download End-Sem Exam Hall Ticket",
    category: "Hall Ticket",
    dueDate: "Aug 08, 2026",
    priority: "High",
    status: "Pending",
    route: "/student/examinations",
  },
];

export const MOCK_EVENTS: EventItem[] = [
  {
    id: "evt-1",
    title: "End-Semester Examinations Commencement",
    category: "Examination",
    date: "Aug 08, 2026",
    time: "10:00 AM",
    location: "Exam Block B",
    priority: "High",
    description: "Official end-semester theory examinations for Semester VII.",
  },
  {
    id: "evt-2",
    title: "National Student AI & ML Hackathon",
    category: "Hackathon",
    date: "Aug 15, 2026",
    time: "09:00 AM",
    location: "Auditorium & Innovation Hub",
    priority: "Medium",
    description: "36-hour continuous hackathon with industry mentors.",
  },
  {
    id: "evt-3",
    title: "Google & Microsoft On-Campus Placement Drive",
    category: "Placement",
    date: "Aug 22, 2026",
    time: "09:30 AM",
    location: "Placement Complex Block C",
    priority: "High",
    description: "Technical Round 1 & Coding Assessment for B.Tech CSE.",
  },
  {
    id: "evt-4",
    title: "AWS Cloud Architecture & Kubernetes Workshop",
    category: "Workshop",
    date: "Aug 18, 2026",
    time: "02:00 PM",
    location: "Seminar Hall 2",
    priority: "Medium",
    description: "Hands-on training session on AWS ECS, EKS, and Lambda.",
  },
  {
    id: "evt-5",
    title: "Independence Day Celebrations & Flag Hoisting",
    category: "Holiday",
    date: "Aug 15, 2026",
    time: "08:00 AM",
    location: "Main Parade Ground",
    priority: "Low",
    description: "Annual Independence Day flag hoisting followed by cultural events.",
  },
];

export const MOCK_ATTENDANCE_SNAPSHOT: AttendanceSnapshot = {
  overallPercentage: 88.5,
  shortageCount: 1,
  classesNeededFor85: 0,
  riskStatus: "Safe",
  totalClassesConducted: 155,
  totalClassesAttended: 137,
  todayAttendance: "2/2 Marked Present",
};

export const MOCK_EXAM_SNAPSHOT: ExamSnapshot = {
  cgpa: 8.45,
  sgpa: 8.60,
  hallTicketStatus: "Generated & Signed",
  courseRegistrationStatus: "Approved & Locked",
  examRegistrationStatus: "Completed",
  upcomingExamSubject: "Theory of Computation (CS403)",
  upcomingExamDate: "Aug 08, 2026 (10:00 AM - 01:00 PM)",
};

export const MOCK_FINANCE_SNAPSHOT: FinanceSnapshot = {
  feesPaid: 120000,
  feesPending: 0,
  totalFees: 120000,
  scholarshipStatus: "Merit Scholarship Sanctioned (₹25,000)",
  fineAmount: 0,
  dueDate: "Nov 01, 2026",
  paymentStatus: "Paid",
};

export const MOCK_LMS_SNAPSHOT: LmsSnapshot = {
  registeredCoursesCount: 6,
  pendingAssignmentsCount: 2,
  pendingQuizCount: 1,
  recentNotes: [
    { title: "Distributed Consensus Algorithms (Raft & Paxos)", subject: "CS401", date: "Aug 01" },
    { title: "Public Key Cryptography & RSA Proofs", subject: "CS402", date: "Jul 30" },
    { title: "Turing Machines & Decidability Classifications", subject: "CS403", date: "Jul 28" },
  ],
  learningProgressPercentage: 78,
};

export const MOCK_LIBRARY_SNAPSHOT: LibrarySnapshot = {
  booksIssued: 3,
  booksDue: 0,
  nextDueDate: "Aug 12, 2026",
  fineAmount: 0,
  digitalLibraryHours: 42,
};

export const MOCK_HOSTEL_SNAPSHOT: HostelSnapshot = {
  roomNumber: "B-304",
  block: "Aryabhata Boys Hostel",
  messMenuToday: {
    breakfast: "Idli, Vada, Sambhar & Coffee",
    lunch: "Paneer Butter Masala, Dal Tadka, Rice & Roti",
    snacks: "Veg Cutlet & Tea",
    dinner: "Veg Biryani / Chicken Curry & Ice Cream",
  },
  gatePassStatus: "None Active",
  hostelNotice: "Night out gate passes require warden clearance 24h prior.",
};

export const MOCK_TRANSPORT_SNAPSHOT: TransportSnapshot = {
  busNumber: "Route #12 (KA-05-EX-4920)",
  driverName: "Mr. Satish Kumar",
  driverPhone: "+91 98765 43210",
  currentLocation: "Near Cyber City Flyover (3.4 km away)",
  eta: "12 mins",
  todaysRoute: "Main Campus ↔ Central Railway Station via MG Road",
};

export const MOCK_PLACEMENT_SNAPSHOT: PlacementSnapshot = {
  profileCompletionPct: 92,
  resumeStatus: "Approved",
  eligibleCompaniesCount: 14,
  upcomingDrivesCount: 2,
  applicationsSubmittedCount: 6,
};

export const MOCK_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: "ann-1",
    title: "Semester VII End-Semester Examination Timetable Official Release",
    category: "Exam",
    date: "Aug 01, 2026",
    unread: true,
    isPinned: true,
    content: "The Controller of Examinations has published the final end-semester examination timetable. Verify subject codes on your student portal.",
    author: "Controller of Examinations",
  },
  {
    id: "ann-2",
    title: "Departmental Research Project Proposal Submission Guidelines",
    category: "Department",
    date: "Jul 31, 2026",
    unread: true,
    isPinned: false,
    content: "All Final Year B.Tech CSE students must submit their capstone project phase-1 proposals to their respective guide.",
    author: "HOD - CSE",
  },
  {
    id: "ann-3",
    title: "State Merit Scholarship Disbursement Credited to Fee Ledger",
    category: "Scholarship",
    date: "Jul 28, 2026",
    unread: false,
    isPinned: false,
    content: "Approved scholarship amounts have been adjusted against term fees.",
    author: "Financial Aid Office",
  },
  {
    id: "ann-4",
    title: "Google Software Engineering Campus Hiring Drive Notification",
    category: "Placement",
    date: "Jul 26, 2026",
    unread: false,
    isPinned: false,
    content: "Registration portal is open for CSE students with CGPA 7.5 and above.",
    author: "Training & Placement Cell",
  },
  {
    id: "ann-5",
    title: "Independence Day Holiday & Campus Flag Hoisting Notice",
    category: "General Circular",
    date: "Jul 25, 2026",
    unread: false,
    isPinned: false,
    content: "Campus will remain closed for lectures on August 15th.",
    author: "Registrar Office",
  },
];

export const MOCK_RECENT_ACTIVITIES: RecentActivityItem[] = [
  {
    id: "act-1",
    type: "Fee",
    title: "Semester VII Tuition Fee Receipt Generated (₹1,20,000)",
    timestamp: "2 hours ago",
    status: "Completed",
  },
  {
    id: "act-2",
    type: "Attendance",
    title: "Attendance Marked Present in CS401 Distributed Systems",
    timestamp: "3 hours ago",
    status: "Submitted",
  },
  {
    id: "act-3",
    type: "Assignment",
    title: "Submitted Lab Task #2: AES Encryption Algorithm",
    timestamp: "Yesterday",
    status: "Submitted",
  },
  {
    id: "act-4",
    type: "Library",
    title: "Borrowed 'Clean Code: Handbook of Agile Software Craftsmanship'",
    timestamp: "2 days ago",
    status: "Issued",
  },
  {
    id: "act-5",
    type: "Hall Ticket",
    title: "End-Semester Hall Ticket Downloaded & Digitally Signed",
    timestamp: "3 days ago",
    status: "Published",
  },
  {
    id: "act-6",
    type: "Leave",
    title: "Medical Leave Approved by HOD Dr. K. S. Ramanujam",
    timestamp: "4 days ago",
    status: "Completed",
  },
  {
    id: "act-7",
    type: "Result",
    title: "Mid-Term Internal Score Published for CS402 Cryptography (27/30)",
    timestamp: "5 days ago",
    status: "Published",
  },
];
