import { StudentProfileData } from "./types";

export const MOCK_STUDENT_PROFILE: StudentProfileData = {
  id: "STU-2022-8941",
  rollNumber: "22CS101",
  registrationNumber: "REG-2022-CSE-0914",
  admissionNumber: "ADM-2022-0491",
  name: "Sai Teja Varma",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
  initials: "ST",
  department: "Computer Science & Engineering",
  departmentCode: "CSE",
  program: "Bachelor of Technology",
  degree: "B.Tech",
  branch: "Computer Science & Engineering",
  section: "Section A",
  currentSemester: 5,
  totalSemesters: 8,
  batch: "2022 - 2026",
  academicYear: "2024 - 2025",
  admissionType: "Merit (State EAMCET Rank #1420)",
  status: "Active",
  enrollmentNumber: "2022-CSE-0491",
  cgpa: 8.92,
  maxCgpa: 10.0,
  rank: 4,
  totalStudentsInBatch: 180,
  attendancePercentage: 88.5,
  feeStatus: "Paid",
  feePendingAmount: 0,
  libraryBooksIssued: 3,
  libraryOverdueCount: 0,
  scholarshipName: "State Merit Excellence Scholarship",
  scholarshipAmount: 45000,
  activeBacklogs: 0,
  creditsEarned: 114,
  totalRequiredCredits: 160,

  academicAdvisor: {
    name: "Dr. Rajesh Kumar",
    designation: "Professor & HOD, CSE Department",
    email: "rajesh.kumar@edusuite.edu.in",
    phone: "+91 98490 12345",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop",
  },

  personal: {
    gender: "Male",
    dob: "2004-06-15",
    bloodGroup: "O+ Positive",
    nationality: "Indian",
    religion: "Hinduism",
    category: "General (OC)",
    phone: "+91 98765 43210",
    email: "sai.teja@student.edusuite.edu.in",
    aadharNumber: "4589 1234 9876",
    passportNumber: "Z9814520",
    emergencyContact: {
      name: "S. Anitha (Mother)",
      relationship: "Mother",
      phone: "+91 99887 76655",
    },
    languages: ["English", "Telugu", "Hindi"],
    maritalStatus: "Single",
  },

  parent: {
    father: {
      name: "S. Venkat Rao",
      occupation: "Senior Systems Engineer (MNC)",
      annualIncome: "₹ 14,50,000 / year",
      phone: "+91 98480 11223",
      email: "venkat.s@gmail.com",
    },
    mother: {
      name: "S. Anitha",
      occupation: "High School Vice Principal",
      annualIncome: "₹ 8,20,000 / year",
      phone: "+91 99887 76655",
      email: "anitha.s@gmail.com",
    },
    guardian: {
      name: "R. K. Varma",
      relationship: "Uncle (Local Guardian)",
      phone: "+91 94400 33445",
      email: "rkvarma@outlook.com",
      address: "Plot 42, Jubilee Hills Phase 3, Hyderabad, Telangana",
    },
  },

  address: {
    permanent: {
      street: "Door No. 12-4-89, Green Meadows Colony",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      pincode: "530017",
      country: "India",
    },
    current: {
      street: "Hostel Block B, Room 304, EduSuite Campus",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500032",
      country: "India",
    },
    googleMaps: {
      latitude: 17.4486,
      longitude: 78.3742,
      embedUrl: "https://maps.google.com/maps?q=17.4486,78.3742&z=15&output=embed",
    },
  },

  currentSubjects: [
    { code: "CS501", name: "Design & Analysis of Algorithms", type: "Theory", credits: 4, faculty: "Dr. Rajesh Kumar", attendance: 92, grade: "A+" },
    { code: "CS502", name: "Database Management Systems", type: "Theory", credits: 4, faculty: "Prof. Ananya Roy", attendance: 88, grade: "A" },
    { code: "CS503", name: "Operating Systems Architecture", type: "Theory", credits: 3, faculty: "Dr. K. V. Sharma", attendance: 85, grade: "B+" },
    { code: "CS504", name: "Computer Networks & Security", type: "Theory", credits: 3, faculty: "Dr. P. Suresh", attendance: 90, grade: "A" },
    { code: "CS505L", name: "DBMS & SQL Laboratory", type: "Lab", credits: 2, faculty: "Prof. Ananya Roy", attendance: 96, grade: "O" },
    { code: "CS506L", name: "Algorithms Simulation Lab", type: "Lab", credits: 2, faculty: "Dr. Rajesh Kumar", attendance: 94, grade: "O" },
    { code: "CS507E", name: "Cloud Computing & AWS Elective", type: "Elective", credits: 3, faculty: "Mr. M. Srinivas", attendance: 78, grade: "A" },
  ],

  semesterResults: [
    { semester: 1, sgpa: 8.75, cgpa: 8.75, creditsAttempted: 22, creditsEarned: 22, status: "Pass", monthYear: "Jan 2023" },
    { semester: 2, sgpa: 9.10, cgpa: 8.93, creditsAttempted: 23, creditsEarned: 23, status: "Pass", monthYear: "Jun 2023" },
    { semester: 3, sgpa: 8.85, cgpa: 8.90, creditsAttempted: 24, creditsEarned: 24, status: "Pass", monthYear: "Jan 2024" },
    { semester: 4, sgpa: 8.98, cgpa: 8.92, creditsAttempted: 24, creditsEarned: 24, status: "Pass", monthYear: "Jun 2024" },
    { semester: 5, sgpa: 9.05, cgpa: 8.95, creditsAttempted: 21, creditsEarned: 21, status: "Pass", monthYear: "Jan 2025" },
  ],

  documents: [
    { id: "DOC-01", title: "Aadhar Card Verification", category: "Identity", fileName: "Aadhar_SaiTeja.pdf", fileSize: "1.4 MB", uploadDate: "2022-08-10", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-02", title: "SSC / 10th Marks Memo", category: "Academic", fileName: "SSC_Marksheet_Original.pdf", fileSize: "2.1 MB", uploadDate: "2022-08-10", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-03", title: "Intermediate / 12th Marks Memo", category: "Academic", fileName: "Inter_12th_Certificate.pdf", fileSize: "2.8 MB", uploadDate: "2022-08-10", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-04", title: "Transfer Certificate (TC)", category: "Transfer", fileName: "TC_College_Original.pdf", fileSize: "1.1 MB", uploadDate: "2022-08-12", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-05", title: "Migration Certificate", category: "Transfer", fileName: "Migration_Certificate.pdf", fileSize: "950 KB", uploadDate: "2022-08-15", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-06", title: "Category Certificate", category: "Category", fileName: "General_Category_Declaration.pdf", fileSize: "820 KB", uploadDate: "2022-08-15", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-07", title: "Income Certificate 2024-25", category: "Financial", fileName: "Income_Cert_2024.pdf", fileSize: "1.6 MB", uploadDate: "2024-06-20", status: "Verified", fileUrl: "#", version: "v2.0" },
    { id: "DOC-08", title: "Bonafide Conduct Certificate", category: "Institutional", fileName: "Bonafide_Sem5_Signed.pdf", fileSize: "640 KB", uploadDate: "2024-07-01", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-09", title: "Passport Copy", category: "Identity", fileName: "Passport_SaiTeja.pdf", fileSize: "3.2 MB", uploadDate: "2023-02-14", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-10", title: "Official Photo Stamp", category: "Photo", fileName: "Passport_Photo_HD.jpg", fileSize: "450 KB", uploadDate: "2022-08-01", status: "Verified", fileUrl: "#", version: "v1.0" },
    { id: "DOC-11", title: "Digital Signature Specimen", category: "Signature", fileName: "Signature_Specimen.png", fileSize: "180 KB", uploadDate: "2022-08-01", status: "Verified", fileUrl: "#", version: "v1.0" },
  ],

  medical: {
    bloodGroup: "O+ Positive",
    allergies: ["Penicillin", "Dust Mites"],
    medicalConditions: ["Mild Asthmatic Tendency (Uses Inhaler as needed)"],
    insurancePolicyNumber: "POL-STAR-8819204",
    insuranceProvider: "Star Health & Allied Campus Shield",
    validTill: "2026-07-31",
    campusDoctorName: "Dr. M. S. Reddi, MD",
    campusDoctorPhone: "+91 94411 22334",
    disabilityDetails: "None (Nil)",
    vaccinations: [
      { name: "COVID-19 Covishield Dose 1 & 2", date: "2021-11-20", status: "Completed" },
      { name: "COVID-19 Booster Precaution Dose", date: "2022-09-15", status: "Completed" },
      { name: "Hepatitis B Vaccination Series", date: "2023-01-10", status: "Completed" },
      { name: "Tetanus Toxoid Annual Booster", date: "2024-05-12", status: "Completed" },
    ],
  },

  achievements: [
    { id: "ACH-101", title: "Winner - National AI Hackathon 2024", category: "Hackathons", issuedBy: "IIT Hyderabad & Microsoft", date: "Oct 2024", description: "Secured 1st Prize out of 250 teams for developing an automated Indian Rail Logistics AI Tracker.", badgeColor: "bg-amber-500/10 text-amber-600 border-amber-500/20" },
    { id: "ACH-102", title: "AWS Certified Solutions Architect", category: "Certifications", issuedBy: "Amazon Web Services (AWS)", date: "Aug 2024", description: "Passed with 890/1000 score verifying enterprise cloud infrastructure competency.", badgeColor: "bg-blue-500/10 text-blue-600 border-blue-500/20" },
    { id: "ACH-103", title: "Full Stack Developer Summer Intern", category: "Internships", issuedBy: "Oracle India R&D Center", date: "May - Jul 2024", description: "Built microservices for enterprise ERP cloud billing engine using React & Spring Boot.", badgeColor: "bg-purple-500/10 text-purple-600 border-purple-500/20" },
    { id: "ACH-104", title: "IEEE International Conference Paper", category: "Research Papers", issuedBy: "IEEE Computer Society", date: "Dec 2024", description: "Co-authored 'Edge Computing in Smart Campus Micro-grids' presented in Tokyo IEEE Summit.", badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-500/20" },
    { id: "ACH-105", title: "Pre-Placement Offer (PPO) - ₹ 18 LPA", category: "Placement Offers", issuedBy: "Microsoft India", date: "Nov 2024", description: "Offered Software Engineer role at Microsoft India R&D Center, Hyderabad.", badgeColor: "bg-indigo-500/10 text-indigo-600 border-indigo-500/20" },
    { id: "ACH-106", title: "Inter-College Table Tennis Champion", category: "Sports", issuedBy: "University Sports Board", date: "Feb 2024", description: "Gold medalist in Singles Table Tennis Tournament across 40 regional engineering colleges.", badgeColor: "bg-rose-500/10 text-rose-600 border-rose-500/20" },
  ],

  disciplinary: [
    { id: "DISC-01", date: "2023-03-14", type: "Positive Behaviour", title: "Library Merit Commendation", description: "Commended for exemplary conduct and organizing digital cataloging drive.", actionTaken: "Awarded Merit Points +50", status: "Commended", issuedBy: "Chief Librarian" },
    { id: "DISC-02", date: "2023-09-10", type: "Warning", title: "Hostel Late Entry Logged", description: "Returned 15 minutes past curfew post hackathon preparation.", actionTaken: "Verbal Warning issued & logged", status: "Resolved", issuedBy: "Chief Warden Block B" },
  ],

  attendanceSummary: {
    overallPercentage: 88.5,
    monthly: [
      { month: "Aug", percentage: 92, present: 23, total: 25 },
      { month: "Sep", percentage: 86, present: 24, total: 28 },
      { month: "Oct", percentage: 90, present: 27, total: 30 },
      { month: "Nov", percentage: 84, present: 21, total: 25 },
      { month: "Dec", percentage: 91, present: 20, total: 22 },
      { month: "Jan", percentage: 88, present: 22, total: 25 },
    ],
    subjectWise: [
      { code: "CS501", subject: "Design & Analysis of Algorithms", attended: 46, total: 50, percentage: 92.0, status: "Normal" },
      { code: "CS502", subject: "Database Management Systems", attended: 44, total: 50, percentage: 88.0, status: "Normal" },
      { code: "CS503", subject: "Operating Systems Architecture", attended: 34, total: 40, percentage: 85.0, status: "Normal" },
      { code: "CS504", subject: "Computer Networks & Security", attended: 36, total: 40, percentage: 90.0, status: "Normal" },
      { code: "CS505L", subject: "DBMS & SQL Laboratory", attended: 24, total: 25, percentage: 96.0, status: "Normal" },
      { code: "CS506L", subject: "Algorithms Simulation Lab", attended: 23, total: 25, percentage: 92.0, status: "Normal" },
      { code: "CS507E", subject: "Cloud Computing & AWS Elective", attended: 26, total: 33, percentage: 78.8, status: "Normal" },
    ],
    leaves: [
      { id: "LEV-881", type: "Medical Leave", startDate: "2024-09-12", endDate: "2024-09-14", days: 3, reason: "Seasonal Viral Fever with prescription from Doctor", status: "Approved" },
      { id: "LEV-942", type: "Duty Leave (OD)", startDate: "2024-10-18", endDate: "2024-10-21", days: 4, reason: "Representing College in IIT Hyderabad Hackathon", status: "Approved" },
    ],
    heatmap: Array.from({ length: 30 }, (_, i) => ({
      date: `2025-01-${String(i + 1).padStart(2, "0")}`,
      status: i % 7 === 0 ? "H" : i % 11 === 0 ? "A" : i % 15 === 0 ? "L" : "P",
    })),
  },

  feesSummary: {
    totalFee: 145000,
    paidFee: 145000,
    pendingFee: 0,
    scholarshipConcession: 45000,
    installments: [
      { installmentNo: 1, title: "Semester 5 Tuition & Academic Fee", dueDate: "2024-07-15", amount: 75000, status: "Paid" },
      { installmentNo: 2, title: "Hostel & Mess Amenities Fee", dueDate: "2024-07-15", amount: 45000, status: "Paid" },
      { installmentNo: 3, title: "Lab & Library Development Charge", dueDate: "2024-08-01", amount: 25000, status: "Paid" },
    ],
    transactions: [
      { receiptNo: "RCP-2024-99120", date: "2024-07-12", mode: "HDFC NetBanking (Ref #TXN88912)", amount: 75000, description: "Sem 5 Tuition Fee Payment", status: "Successful" },
      { receiptNo: "RCP-2024-99184", date: "2024-07-14", mode: "UPI (Google Pay)", amount: 45000, description: "Hostel & Mess Term 1 Fee", status: "Successful" },
      { receiptNo: "RCP-2024-99410", date: "2024-07-30", mode: "ICICI Debit Card", amount: 25000, description: "Lab & Library Fee", status: "Successful" },
    ],
  },

  librarySummary: {
    booksIssuedCount: 3,
    dueBooksCount: 0,
    totalFine: 0,
    digitalUsageHours: 142,
    issuedBooks: [
      { id: "LIB-9012", title: "Introduction to Algorithms (CLRS) 4th Edition", author: "Cormen, Leiserson, Rivest", isbn: "978-0262046305", issueDate: "2024-12-10", dueDate: "2025-02-10", renewCount: 1, fine: 0 },
      { id: "LIB-9418", title: "Database System Concepts 7th Edition", author: "Silberschatz, Korth, Sudarshan", isbn: "978-0078022159", issueDate: "2025-01-05", dueDate: "2025-02-05", renewCount: 0, fine: 0 },
      { id: "LIB-9821", title: "Computer Networking: A Top-Down Approach", author: "Kurose & Ross", isbn: "978-0133594140", issueDate: "2025-01-12", dueDate: "2025-02-12", renewCount: 0, fine: 0 },
    ],
    reservations: [
      { title: "Designing Data-Intensive Applications", reservedDate: "2025-01-20", queuePosition: 1 },
    ],
  },

  hostel: {
    block: "Block B (Boys Engineering)",
    roomNo: "Room 304",
    floor: "3rd Floor",
    roomType: "2-Sharing AC Deluxe Room",
    messName: "North & South Hybrid Dining Hall A",
    messPlan: "Unlimited Standard Pure Veg + Non-Veg 3x/week",
    wardenName: "Prof. S. R. Murthy",
    wardenPhone: "+91 98499 11002",
    outingPasses: [
      { id: "PASS-1029", destination: "City Mall & Technical Book Center", outTime: "2025-01-26 14:00", expectedInTime: "2025-01-26 20:30", status: "Approved" },
      { id: "PASS-0941", destination: "Home Visit - Visakhapatnam", outTime: "2025-01-12 18:00", expectedInTime: "2025-01-15 08:00", status: "Used" },
    ],
  },

  transport: {
    busNumber: "Bus No. 14 (Route 4B)",
    routeName: "Miyapur Metro -> Gachibowli -> Campus Express",
    driverName: "K. Nageswara Rao",
    driverPhone: "+91 94900 88776",
    pickupPoint: "Gachibowli Flyover Junction",
    dropPoint: "EduSuite Main Gate Terminal",
    pickupTime: "07:45 AM Daily",
    passValidity: "Valid till June 2025 (Annual Pass #TP-884)",
    routeStops: [
      { stopName: "Miyapur Metro Station", time: "07:20 AM", passed: true },
      { stopName: "Chanda Nagar Hub", time: "07:32 AM", passed: true },
      { stopName: "Gachibowli Flyover", time: "07:45 AM", passed: true },
      { stopName: "Wipro Circle", time: "07:55 AM", passed: true },
      { stopName: "EduSuite University Campus", time: "08:15 AM", passed: true },
    ],
    currentBusLocation: {
      lat: 17.4486,
      lng: 78.3742,
      speed: "42 km/h",
      nextStop: "EduSuite University Campus",
      etaMinutes: 4,
    },
  },

  timeline: [
    { id: "TL-01", date: "Aug 2022", title: "Enrolled in B.Tech Computer Science", category: "Admission", description: "Successfully admitted via EAMCET State Rank 1420.", icon: "GraduationCap" },
    { id: "TL-02", date: "Jan 2023", title: "Completed Semester 1 - SGPA 8.75", category: "Exam Results", description: "Cleared all 7 subjects in first attempt.", icon: "Award" },
    { id: "TL-03", date: "Jun 2023", title: "Completed Semester 2 - SGPA 9.10", category: "Exam Results", description: "Secured Department Top 5 Rank.", icon: "Trophy" },
    { id: "TL-04", date: "Oct 2023", title: "Selected for Microsoft Hackathon", category: "Achievements", description: "Shortlisted for National Finals.", icon: "Zap" },
    { id: "TL-05", date: "May 2024", title: "Oracle R&D Internship", category: "Placement", description: "Joined Oracle India Cloud Engine division.", icon: "Briefcase" },
    { id: "TL-06", date: "Nov 2024", title: "Microsoft PPO Secured", category: "Placement", description: "Accepted ₹ 18 LPA Pre-Placement Offer.", icon: "CheckCircle2" },
    { id: "TL-07", date: "Jan 2025", title: "Semester 5 Registration Completed", category: "Semester Promotion", description: "Promoted to 3rd Year 2nd Semester.", icon: "BookOpen" },
  ],

  settings: {
    profileVisibility: "Internal",
    emailNotifications: true,
    smsAlerts: true,
    twoFactorEnabled: true,
    language: "English (US)",
    theme: "light",
    activeSessions: [
      { device: "MacBook Pro 16 (Chrome 122)", ip: "103.15.24.12", location: "Hyderabad, India", lastActive: "Just now", current: true },
      { device: "iPhone 15 Pro (EduSuite App)", ip: "49.207.18.91", location: "Hyderabad, India", lastActive: "2 hours ago", current: false },
    ],
  },
};
