import { Webinar, CertificateItem, RecordingItem, ScheduleTimelineItem } from "./types";

export const MOCK_KPIS = [
  {
    id: "upcoming",
    title: "Upcoming Webinars",
    value: "08",
    subtext: "View all upcoming",
    targetTab: "upcoming" as const,
  },
  {
    id: "registered",
    title: "Registered Webinars",
    value: "05",
    subtext: "View your registrations",
    targetTab: "registered" as const,
  },
  {
    id: "live",
    title: "Live Sessions",
    value: "01",
    subtext: "Join live now",
    targetTab: "live" as const,
  },
  {
    id: "completed",
    title: "Completed Sessions",
    value: "12",
    subtext: "View completed",
    targetTab: "completed" as const,
  },
  {
    id: "certificates",
    title: "Certificates Earned",
    value: "06",
    subtext: "View certificates",
    targetTab: "certificates" as const,
  },
  {
    id: "hours",
    title: "Learning Hours",
    value: "28 hrs",
    subtext: "Total time spent",
    targetTab: "upcoming" as const,
  },
  {
    id: "speakers",
    title: "Expert Speakers",
    value: "14",
    subtext: "Learn from experts",
    targetTab: "upcoming" as const,
  },
];

export const MOCK_UPCOMING_WEBINARS: Webinar[] = [
  {
    id: "web-1",
    title: "Introduction to Artificial Intelligence",
    category: "AI & ML",
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "10" },
    startDate: "2026-08-10",
    displayDate: "Aug 10, 2026",
    displayTime: "11:00 AM - 12:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-1",
      name: "Dr. Priya Sharma",
      role: "AI Research Scientist",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
      organization: "Google AI",
      bio: "Dr. Priya Sharma is a principal AI researcher specializing in deep learning and NLP architectures.",
    },
    description: "Explore the core concepts of artificial intelligence, neural networks, machine learning algorithms, and real-world industrial applications.",
    agenda: [
      "Introduction to Neural Networks & Deep Learning",
      "Overview of Supervised & Unsupervised Learning",
      "Building your first ML model with Python",
      "Q&A and Career Guidance in Artificial Intelligence",
    ],
    totalSeats: 150,
    registeredCount: 120,
    seatsLeft: 30,
    isRegistered: true,
    isBookmarked: true,
  },
  {
    id: "web-2",
    title: "Cloud Computing for Beginners",
    category: "Cloud",
    bannerImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "12" },
    startDate: "2026-08-12",
    displayDate: "Aug 12, 2026",
    displayTime: "02:00 PM - 03:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-2",
      name: "Mr. Arjun Reddy",
      role: "Cloud Architect",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      organization: "Amazon Web Services",
      bio: "Arjun Reddy is a Senior Solutions Architect with deep expertise in cloud migration and DevOps automation.",
    },
    description: "Learn fundamental cloud deployment models, IaaS vs PaaS vs SaaS, virtual machines, containerization, and AWS architecture basics.",
    agenda: [
      "Understanding AWS, Azure, and Google Cloud Infrastructure",
      "Virtual Private Cloud (VPC) & Security Best Practices",
      "Deploying your first Cloud App",
      "Q&A Session",
    ],
    totalSeats: 150,
    registeredCount: 98,
    seatsLeft: 52,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-live-1",
    title: "The Future of AI in Automotive Industry",
    category: "AI & ML",
    bannerImage: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=80",
    status: "live",
    dateBadge: { month: "AUG", day: "08" },
    startDate: "2026-08-08",
    displayDate: "Aug 08, 2026",
    displayTime: "04:00 PM - 05:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-raghav",
      name: "Dr. Raghav Menon",
      role: "Head of AI, Tesla India",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
      organization: "Tesla",
      bio: "Dr. Raghav Menon leads autonomous driving AI initiatives at Tesla India with 15+ years of experience in computer vision.",
    },
    description: "Dive into autonomous driving neural networks, computer vision perception, sensor fusion, and reinforcement learning in modern electric vehicle technologies.",
    agenda: [
      "Computer Vision & LiDAR Sensor Fusion",
      "Real-time Edge AI Inference on Vehicles",
      "Reinforcement Learning for Autonomous Navigation",
      "Career Opportunities in Automotive Tech",
    ],
    totalSeats: 500,
    registeredCount: 180,
    seatsLeft: 320,
    isRegistered: true,
    isFeatured: true,
  },
  {
    id: "web-3",
    title: "Python for Data Analysis",
    category: "Python",
    bannerImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "14" },
    startDate: "2026-08-14",
    displayDate: "Aug 14, 2026",
    displayTime: "10:00 AM - 11:30 AM",
    duration: "1h 30m",
    speaker: {
      id: "spk-3",
      name: "Dr. Karthik Babu",
      role: "Data Scientist",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      organization: "Microsoft",
      bio: "Dr. Karthik Babu leads data science teams specializing in predictive analytics and large-scale data modeling.",
    },
    description: "Master NumPy, Pandas, Matplotlib, and Data Wrangling techniques for exploratory data analysis and statistical modeling.",
    agenda: [
      "Data Manipulation with Pandas DataFrames",
      "Visualizing Complex Trends with Seaborn",
      "Cleaning messy datasets",
      "Live Coding & Notebook sharing",
    ],
    totalSeats: 150,
    registeredCount: 110,
    seatsLeft: 40,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-comp-1",
    title: "Full Stack Web Development with React & Node",
    category: "Web Development",
    bannerImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80",
    status: "completed",
    dateBadge: { month: "AUG", day: "01" },
    startDate: "2026-08-01",
    displayDate: "Aug 01, 2026",
    displayTime: "05:00 PM - 06:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-5",
      name: "Vikram Malhotra",
      role: "Lead Full Stack Engineer",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
      organization: "Meta",
      bio: "Vikram is a senior engineer at Meta focusing on high-performance frontend frameworks and distributed APIs.",
    },
    description: "Comprehensive workshop covering modern React architecture, state management, REST API integration, and Node.js microservices.",
    agenda: [
      "React 19 & Server Components Overview",
      "Building scalable REST APIs with Express",
      "Database ORM & Authentication",
    ],
    totalSeats: 300,
    registeredCount: 300,
    seatsLeft: 0,
    isRegistered: true,
    isBookmarked: true,
  },
  {
    id: "web-4",
    title: "Cyber Security Essentials",
    category: "Cyber Security",
    bannerImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "16" },
    startDate: "2026-08-16",
    displayDate: "Aug 16, 2026",
    displayTime: "03:00 PM - 04:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-4",
      name: "Ms. Sneha Kulkarni",
      role: "Cyber Security Expert",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
      organization: "Palo Alto Networks",
      bio: "Sneha is a certified ethical hacker and security consultant advising Fortune 500 companies.",
    },
    description: "Protect systems against network vulnerabilities, phishing attacks, malware, and zero-day threats in enterprise environments.",
    agenda: [
      "OWASP Top 10 Web Vulnerabilities",
      "Network Penetration Testing Basics",
      "Data Encryption & Key Management",
      "Interactive Q&A",
    ],
    totalSeats: 100,
    registeredCount: 75,
    seatsLeft: 25,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-java-1",
    title: "Advanced Java & Spring Boot Microservices",
    category: "Java",
    bannerImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "18" },
    startDate: "2026-08-18",
    displayDate: "Aug 18, 2026",
    displayTime: "11:00 AM - 12:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-java",
      name: "Rajesh Varma",
      role: "Principal Java Architect",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
      organization: "Oracle",
      bio: "Rajesh has 14+ years of experience designing high-throughput enterprise systems with Java and Spring.",
    },
    description: "Master Java 21 features, Spring Boot 3 microservices architecture, JPA/Hibernate performance, and distributed caching.",
    agenda: [
      "Java 21 Virtual Threads & Concurrency",
      "Spring Boot 3 REST API Design",
      "Microservice Communication with Kafka",
    ],
    totalSeats: 200,
    registeredCount: 140,
    seatsLeft: 60,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-devops-1",
    title: "CI/CD Pipeline Automation & Kubernetes",
    category: "DevOps",
    bannerImage: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "20" },
    startDate: "2026-08-20",
    displayDate: "Aug 20, 2026",
    displayTime: "02:00 PM - 03:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-devops",
      name: "Ananya Deshmukh",
      role: "DevOps Lead",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
      organization: "Red Hat",
      bio: "Ananya specializes in containerization, GitOps, and automated cloud deployments.",
    },
    description: "Build robust Docker containers, automate CI/CD pipelines with GitHub Actions, and orchestrate deployments with Kubernetes.",
    agenda: [
      "Docker Multi-Stage Builds",
      "GitHub Actions CI/CD Workflows",
      "Kubernetes Cluster Deployment",
    ],
    totalSeats: 180,
    registeredCount: 130,
    seatsLeft: 50,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-ds-1",
    title: "Data Science & Predictive Analytics",
    category: "Data Science",
    bannerImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "22" },
    startDate: "2026-08-22",
    displayDate: "Aug 22, 2026",
    displayTime: "10:00 AM - 11:30 AM",
    duration: "1h 30m",
    speaker: {
      id: "spk-ds",
      name: "Siddharth Mehta",
      role: "Chief Data Scientist",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      organization: "IBM",
      bio: "Siddharth guides data science initiatives across predictive analytics and NLP.",
    },
    description: "Learn statistical hypothesis testing, machine learning regression, feature engineering, and model evaluation.",
    agenda: [
      "Exploratory Data Analysis Best Practices",
      "Scikit-Learn Machine Learning Pipeline",
      "Model Evaluation Metrics",
    ],
    totalSeats: 250,
    registeredCount: 210,
    seatsLeft: 40,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-placement-1",
    title: "Campus Placement Masterclass & HR Strategy",
    category: "Placement",
    bannerImage: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "24" },
    startDate: "2026-08-24",
    displayDate: "Aug 24, 2026",
    displayTime: "04:00 PM - 05:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-placement",
      name: "Rohan Kapoor",
      role: "Head of University Hiring",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      organization: "TCS",
      bio: "Rohan leads campus recruitment programs across top technical institutes in India.",
    },
    description: "Insider secrets for cracking technical interviews, resume ATS optimization, and HR negotiation strategy.",
    agenda: [
      "Acing Aptitude & Coding Screening Rounds",
      "Crafting an ATS-proof Technical Resume",
      "Behavioral HR Interview Preparation",
    ],
    totalSeats: 400,
    registeredCount: 350,
    seatsLeft: 50,
    isRegistered: true,
    isBookmarked: true,
  },
  {
    id: "web-prep-1",
    title: "System Design & Coding Interview Prep",
    category: "Interview Prep",
    bannerImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "26" },
    startDate: "2026-08-26",
    displayDate: "Aug 26, 2026",
    displayTime: "05:00 PM - 06:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-prep",
      name: "Neha Joshi",
      role: "Tech Lead",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
      organization: "Uber",
      bio: "Neha conducts tech interviews at Uber and mentors software engineers on System Design.",
    },
    description: "Master Data Structures & Algorithms problem solving strategies and high-level System Design principles.",
    agenda: [
      "Two Pointers & Sliding Window Patterns",
      "Designing Scalable Distributed Systems",
      "Mock Interview Walkthrough",
    ],
    totalSeats: 300,
    registeredCount: 220,
    seatsLeft: 80,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-soft-1",
    title: "Professional Communication & Leadership",
    category: "Soft Skills",
    bannerImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "28" },
    startDate: "2026-08-28",
    displayDate: "Aug 28, 2026",
    displayTime: "03:00 PM - 04:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-soft",
      name: "Kavita Rao",
      role: "Corporate Executive Coach",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
      organization: "Deloitte",
      bio: "Kavita coaches engineering managers and students on executive presence and soft skills.",
    },
    description: "Elevate your workplace communication, public speaking, active listening, and team leadership skills.",
    agenda: [
      "Art of Persuasive Presentations",
      "Managing Workplace Conflict",
      "Building Professional Networking Presence",
    ],
    totalSeats: 200,
    registeredCount: 150,
    seatsLeft: 50,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-react-1",
    title: "React 19, Server Components & Next.js",
    category: "React",
    bannerImage: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "30" },
    startDate: "2026-08-30",
    displayDate: "Aug 30, 2026",
    displayTime: "11:00 AM - 12:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-react",
      name: "Manish Kumar",
      role: "Staff Frontend Engineer",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
      organization: "Vercel",
      bio: "Manish contributes to open-source React ecosystem tools and Next.js performance.",
    },
    description: "Explore React 19 Compiler, Server Actions, useActionState hook, and Next.js App Router performance tuning.",
    agenda: [
      "Understanding React Server Components Architecture",
      "Form handling with Server Actions",
      "Optimizing Core Web Vitals",
    ],
    totalSeats: 350,
    registeredCount: 290,
    seatsLeft: 60,
    isRegistered: true,
    isBookmarked: true,
  },
  {
    id: "web-mobile-1",
    title: "Flutter & React Native Mobile App Dev",
    category: "Mobile Development",
    bannerImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "SEP", day: "02" },
    startDate: "2026-09-02",
    displayDate: "Sep 02, 2026",
    displayTime: "02:00 PM - 03:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-mobile",
      name: "Deepak Chawla",
      role: "Mobile App Lead",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
      organization: "Flipkart",
      bio: "Deepak architected mobile apps used by millions of daily active users.",
    },
    description: "Cross-platform iOS and Android mobile development using Flutter, Dart, React Native, and native bridges.",
    agenda: [
      "Flutter State Management with Riverpod",
      "Native Device Hardware Access (Camera, GPS)",
      "Publishing Apps to App Store & Google Play",
    ],
    totalSeats: 180,
    registeredCount: 140,
    seatsLeft: 40,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-blockchain-1",
    title: "Web3, Smart Contracts & Ethereum Development",
    category: "Blockchain",
    bannerImage: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "SEP", day: "04" },
    startDate: "2026-09-04",
    displayDate: "Sep 04, 2026",
    displayTime: "04:00 PM - 05:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-blockchain",
      name: "Tarun Gill",
      role: "Web3 Security Auditor",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
      organization: "Polygon",
      bio: "Tarun audits Solidity smart contracts and decentralised applications (dApps).",
    },
    description: "Build secure Solidity smart contracts, deploy on Ethereum testnets, and integrate dApps with Ethers.js.",
    agenda: [
      "Solidity Fundamentals & Security Pitfalls",
      "Building & Deploying Smart Contracts with Hardhat",
      "Connecting Frontend to Web3 Wallet",
    ],
    totalSeats: 150,
    registeredCount: 95,
    seatsLeft: 55,
    isRegistered: false,
    isBookmarked: false,
  },
];

export const MOCK_FEATURED_WEBINAR: Webinar = {
  id: "web-live-1",
  title: "The Future of AI in Automotive Industry",
  category: "AI & ML",
  subtitle: "Autonomous driving, perception, and computer vision.",
  bannerImage: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=80",
  status: "live",
  dateBadge: { month: "AUG", day: "08" },
  startDate: "2026-08-08",
  displayDate: "Aug 08, 2026",
  displayTime: "04:00 PM - 05:30 PM",
  duration: "1h 30m",
  speaker: {
    id: "spk-raghav",
    name: "Dr. Raghav Menon",
    role: "Head of AI, Tesla India",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    organization: "Tesla",
    bio: "Dr. Raghav Menon leads autonomous driving AI initiatives at Tesla India with 15+ years of experience in computer vision.",
  },
  description: "Dive into autonomous driving neural networks, computer vision perception, sensor fusion, and reinforcement learning in modern electric vehicle technologies.",
  agenda: [
    "Computer Vision & LiDAR Sensor Fusion",
    "Real-time Edge AI Inference on Vehicles",
    "Reinforcement Learning for Autonomous Navigation",
    "Career Opportunities in Automotive Tech",
  ],
  totalSeats: 500,
  registeredCount: 180,
  seatsLeft: 320,
  isRegistered: true,
  isFeatured: true,
};

export const MOCK_TOP_CATEGORIES = [
  { name: "AI & ML", icon: "Cpu" },
  { name: "Python", icon: "Terminal" },
  { name: "Java", icon: "Code" },
  { name: "Cloud", icon: "Cloud" },
  { name: "Cyber Security", icon: "Shield" },
  { name: "DevOps", icon: "Server" },
  { name: "Web Development", icon: "Globe" },
  { name: "Data Science", icon: "BarChart" },
  { name: "Placement", icon: "Briefcase" },
  { name: "Interview Prep", icon: "UserCheck" },
  { name: "Soft Skills", icon: "MessageSquare" },
  { name: "React", icon: "Layers" },
  { name: "Mobile Development", icon: "Smartphone" },
  { name: "Blockchain", icon: "Database" },
];

export const MOCK_SCHEDULE_TIMELINE: ScheduleTimelineItem[] = [
  {
    id: "sch-1",
    dateLabel: "Today, Aug 8",
    title: "AI for Developers",
    time: "11:00 AM - 12:30 PM",
  },
  {
    id: "sch-2",
    dateLabel: "Tomorrow, Aug 9",
    title: "Cloud Computing Basics",
    time: "02:00 PM - 03:30 PM",
  },
  {
    id: "sch-3",
    dateLabel: "Aug 12, 2026",
    title: "Spring Boot Masterclass",
    time: "10:00 AM - 11:30 AM",
  },
  {
    id: "sch-4",
    dateLabel: "Aug 15, 2026",
    title: "Resume Building Workshop",
    time: "04:00 PM - 05:30 PM",
  },
];

export const MOCK_HIGHLIGHTS_ITEMS = [
  {
    id: "hl-1",
    title: "Live Q&A",
    subtitle: "Interact with speakers in real time.",
    icon: "Video",
  },
  {
    id: "hl-2",
    title: "Earn Certificates",
    subtitle: "Get certified after completing webinars.",
    icon: "Award",
  },
  {
    id: "hl-3",
    title: "Recorded Sessions",
    subtitle: "Watch anytime, anywhere.",
    icon: "PlayCircle",
  },
  {
    id: "hl-4",
    title: "Calendar Reminder",
    subtitle: "Never miss important sessions.",
    icon: "Calendar",
  },
  {
    id: "hl-5",
    title: "Expert Speakers",
    subtitle: "Learn from industry professionals.",
    icon: "UserCheck",
  },
];

export const MOCK_CERTIFICATES: CertificateItem[] = [
  {
    id: "cert-1",
    webinarId: "web-106",
    certificateName: "AI & Deep Learning Foundations",
    webinarTitle: "Introduction to Artificial Intelligence",
    issueDate: "Aug 01, 2026",
    issuerName: "EduSuite Pro Technical Academy",
    certificateCode: "CERT-EDU-2026-9012",
    downloadUrl: "/certificates/ai-foundations.pdf",
  },
  {
    id: "cert-2",
    webinarId: "web-107",
    certificateName: "Cloud Infrastructure Architect",
    webinarTitle: "Cloud Computing for Beginners",
    issueDate: "Jul 25, 2026",
    issuerName: "EduSuite Pro Technical Academy",
    certificateCode: "CERT-EDU-2026-8810",
    downloadUrl: "/certificates/cloud-architect.pdf",
  },
];

export const MOCK_RECORDINGS: RecordingItem[] = [
  {
    id: "rec-1",
    webinarId: "web-106",
    title: "Introduction to Artificial Intelligence",
    category: "AI & ML",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    duration: "1h 30m",
    speaker: {
      id: "spk-1",
      name: "Dr. Priya Sharma",
      role: "AI Research Scientist",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    },
    views: 1240,
    recordedDate: "Aug 01, 2026",
    isBookmarked: false,
  },
  {
    id: "rec-2",
    webinarId: "web-107",
    title: "Cloud Computing for Beginners",
    category: "Cloud",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    duration: "1h 30m",
    speaker: {
      id: "spk-2",
      name: "Mr. Arjun Reddy",
      role: "Cloud Architect",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    },
    views: 980,
    recordedDate: "Jul 25, 2026",
    isBookmarked: true,
  },
];
