import { Webinar, CertificateItem, RecordingItem, ScheduleTimelineItem } from "./types";

export const MOCK_KPIS = [
  {
    id: "upcoming",
    title: "Upcoming Webinars",
    value: "08",
    subtext: "View all upcoming",
    targetTab: "upcoming" as const,
  },
  {
    id: "registered",
    title: "Registered Webinars",
    value: "05",
    subtext: "View your registrations",
    targetTab: "registered" as const,
  },
  {
    id: "live",
    title: "Live Sessions",
    value: "01",
    subtext: "Join live now",
    targetTab: "live" as const,
  },
  {
    id: "completed",
    title: "Completed Sessions",
    value: "12",
    subtext: "View completed",
    targetTab: "completed" as const,
  },
  {
    id: "certificates",
    title: "Certificates Earned",
    value: "06",
    subtext: "View certificates",
    targetTab: "certificates" as const,
  },
  {
    id: "hours",
    title: "Learning Hours",
    value: "28 hrs",
    subtext: "Total time spent",
    targetTab: "upcoming" as const,
  },
  {
    id: "speakers",
    title: "Expert Speakers",
    value: "14",
    subtext: "Learn from experts",
    targetTab: "upcoming" as const,
  },
];

export const MOCK_UPCOMING_WEBINARS: Webinar[] = [
  {
    id: "web-1",
    title: "Introduction to Artificial Intelligence",
    category: "AI & ML",
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "10" },
    startDate: "2026-08-10",
    displayTime: "11:00 AM - 12:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-1",
      name: "Dr. Priya Sharma",
      role: "AI Research Scientist",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    },
    description: "Explore the core concepts of artificial intelligence, neural networks, machine learning algorithms, and real-world industrial applications.",
    agenda: [
      "Introduction to Neural Networks & Deep Learning",
      "Overview of Supervised & Unsupervised Learning",
      "Building your first ML model with Python",
      "Q&A and Career Guidance in Artificial Intelligence",
    ],
    totalSeats: 150,
    registeredCount: 120,
    seatsLeft: 30,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-2",
    title: "Cloud Computing for Beginners",
    category: "Cloud",
    bannerImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "12" },
    startDate: "2026-08-12",
    displayTime: "02:00 PM - 03:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-2",
      name: "Mr. Arjun Reddy",
      role: "Cloud Architect",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    },
    description: "Learn fundamental cloud deployment models, IaaS vs PaaS vs SaaS, virtual machines, containerization, and AWS architecture basics.",
    agenda: [
      "Understanding AWS, Azure, and Google Cloud Infrastructure",
      "Virtual Private Cloud (VPC) & Security Best Practices",
      "Deploying your first Cloud App",
      "Q&A Session",
    ],
    totalSeats: 150,
    registeredCount: 98,
    seatsLeft: 52,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-3",
    title: "Python for Data Analysis",
    category: "Python",
    bannerImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "14" },
    startDate: "2026-08-14",
    displayTime: "10:00 AM - 11:30 AM",
    duration: "1h 30m",
    speaker: {
      id: "spk-3",
      name: "Dr. Karthik Babu",
      role: "Data Scientist",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    },
    description: "Master NumPy, Pandas, Matplotlib, and Data Wrangling techniques for exploratory data analysis and statistical modeling.",
    agenda: [
      "Data Manipulation with Pandas DataFrames",
      "Visualizing Complex Trends with Seaborn",
      "Cleaning messy datasets",
      "Live Coding & Notebook sharing",
    ],
    totalSeats: 150,
    registeredCount: 110,
    seatsLeft: 40,
    isRegistered: false,
    isBookmarked: false,
  },
  {
    id: "web-4",
    title: "Cyber Security Essentials",
    category: "Cyber Security",
    bannerImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80",
    status: "upcoming",
    dateBadge: { month: "AUG", day: "16" },
    startDate: "2026-08-16",
    displayTime: "03:00 PM - 04:30 PM",
    duration: "1h 30m",
    speaker: {
      id: "spk-4",
      name: "Ms. Sneha Kulkarni",
      role: "Cyber Security Expert",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
    },
    description: "Protect systems against network vulnerabilities, phishing attacks, malware, and zero-day threats in enterprise environments.",
    agenda: [
      "OWASP Top 10 Web Vulnerabilities",
      "Network Penetration Testing Basics",
      "Data Encryption & Key Management",
      "Interactive Q&A",
    ],
    totalSeats: 100,
    registeredCount: 75,
    seatsLeft: 25,
    isRegistered: false,
    isBookmarked: false,
  },
];

export const MOCK_FEATURED_WEBINAR: Webinar = {
  id: "web-featured",
  title: "The Future of AI in Automotive Industry",
  category: "AI & ML",
  bannerImage: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=80",
  status: "live",
  dateBadge: { month: "AUG", day: "08" },
  startDate: "2026-08-08",
  displayTime: "04:00 PM - 05:30 PM",
  duration: "1h 30m",
  speaker: {
    id: "spk-raghav",
    name: "Dr. Raghav Menon",
    role: "Head of AI, Tesla India",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
  },
  description: "Dive into autonomous driving neural networks, computer vision perception, sensor fusion, and reinforcement learning in modern electric vehicle technologies.",
  agenda: [
    "Computer Vision & LiDAR Sensor Fusion",
    "Real-time Edge AI Inference on Vehicles",
    "Reinforcement Learning for Autonomous Navigation",
    "Career Opportunities in Automotive Tech",
  ],
  totalSeats: 500,
  registeredCount: 180,
  seatsLeft: 320,
  isRegistered: false,
  isFeatured: true,
};

export const MOCK_TOP_CATEGORIES = [
  { name: "AI & ML", icon: "Cpu" },
  { name: "Python", icon: "Terminal" },
  { name: "Java", icon: "Code" },
  { name: "Cloud", icon: "Cloud" },
  { name: "Cyber Security", icon: "Shield" },
  { name: "DevOps", icon: "Server" },
  { name: "Web Development", icon: "Globe" },
  { name: "Data Science", icon: "BarChart" },
  { name: "Placement", icon: "Briefcase" },
  { name: "Interview Prep", icon: "UserCheck" },
  { name: "Soft Skills", icon: "MessageSquare" },
  { name: "React", icon: "Layers" },
  { name: "Mobile Development", icon: "Smartphone" },
  { name: "Blockchain", icon: "Database" },
];

export const MOCK_SCHEDULE_TIMELINE: ScheduleTimelineItem[] = [
  {
    id: "sch-1",
    dateLabel: "Today, Aug 8",
    title: "AI for Developers",
    time: "11:00 AM - 12:30 PM",
  },
  {
    id: "sch-2",
    dateLabel: "Tomorrow, Aug 9",
    title: "Cloud Computing Basics",
    time: "02:00 PM - 03:30 PM",
  },
  {
    id: "sch-3",
    dateLabel: "Aug 12, 2026",
    title: "Spring Boot Masterclass",
    time: "10:00 AM - 11:30 AM",
  },
  {
    id: "sch-4",
    dateLabel: "Aug 15, 2026",
    title: "Resume Building Workshop",
    time: "04:00 PM - 05:30 PM",
  },
];

export const MOCK_HIGHLIGHTS_ITEMS = [
  {
    id: "hl-1",
    title: "Live Q&A",
    subtitle: "Interact with speakers in real time.",
    icon: "Video",
  },
  {
    id: "hl-2",
    title: "Earn Certificates",
    subtitle: "Get certified after completing webinars.",
    icon: "Award",
  },
  {
    id: "hl-3",
    title: "Recorded Sessions",
    subtitle: "Watch anytime, anywhere.",
    icon: "PlayCircle",
  },
  {
    id: "hl-4",
    title: "Calendar Reminder",
    subtitle: "Never miss important sessions.",
    icon: "Calendar",
  },
  {
    id: "hl-5",
    title: "Expert Speakers",
    subtitle: "Learn from industry professionals.",
    icon: "UserCheck",
  },
];

export const MOCK_CERTIFICATES: CertificateItem[] = [
  {
    id: "cert-1",
    webinarId: "web-106",
    certificateName: "AI & Deep Learning Foundations",
    webinarTitle: "Introduction to Artificial Intelligence",
    issueDate: "Aug 01, 2026",
    issuerName: "EduSuite Pro Technical Academy",
    certificateCode: "CERT-EDU-2026-9012",
    downloadUrl: "/certificates/ai-foundations.pdf",
  },
  {
    id: "cert-2",
    webinarId: "web-107",
    certificateName: "Cloud Infrastructure Architect",
    webinarTitle: "Cloud Computing for Beginners",
    issueDate: "Jul 25, 2026",
    issuerName: "EduSuite Pro Technical Academy",
    certificateCode: "CERT-EDU-2026-8810",
    downloadUrl: "/certificates/cloud-architect.pdf",
  },
];

export const MOCK_RECORDINGS: RecordingItem[] = [
  {
    id: "rec-1",
    webinarId: "web-106",
    title: "Introduction to Artificial Intelligence",
    category: "AI & ML",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    duration: "1h 30m",
    speaker: {
      id: "spk-1",
      name: "Dr. Priya Sharma",
      role: "AI Research Scientist",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    },
    views: 1240,
    recordedDate: "Aug 01, 2026",
    isBookmarked: false,
  },
  {
    id: "rec-2",
    webinarId: "web-107",
    title: "Cloud Computing for Beginners",
    category: "Cloud",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    duration: "1h 30m",
    speaker: {
      id: "spk-2",
      name: "Mr. Arjun Reddy",
      role: "Cloud Architect",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    },
    views: 980,
    recordedDate: "Jul 25, 2026",
    isBookmarked: true,
  },
];
