import {
  FeedbackSummaryKPIs,
  ActiveSurveyItem,
  GrievanceCategoryItem,
  StudentServiceItem,
  HistoryRecord,
  GrievanceRecord,
} from "./types";

export const mockFeedbackKPIs: FeedbackSummaryKPIs = {
  facultyFeedbackSubmitted: 14,
  pendingFeedback: 2,
  openGrievances: 1,
  serviceRequests: 3,
};

export const mockFacultyList = [
  { id: "FAC-101", name: "Dr. Rajesh Kumar", department: "Computer Science", subject: "DBMS & Database Systems" },
  { id: "FAC-102", name: "Prof. Ananya Roy", department: "Computer Science", subject: "Operating Systems & Kernel Design" },
  { id: "FAC-103", name: "Dr. Ravi Shankar", department: "Computer Science", subject: "Computer Networks & Protocols" },
  { id: "FAC-104", name: "Dr. A. Sharma", department: "Computer Science", subject: "DAA - Design & Analysis of Algorithms" },
];

export const mockCourseList = [
  { code: "CS301", title: "DBMS (Database Management Systems)", sem: "Semester 5", dept: "Computer Science" },
  { code: "CS302", title: "Operating Systems", sem: "Semester 5", dept: "Computer Science" },
  { code: "CS303", title: "Computer Networks", sem: "Semester 5", dept: "Computer Science" },
  { code: "CS304", title: "DAA (Design & Analysis of Algorithms)", sem: "Semester 5", dept: "Computer Science" },
];

export const mockActiveSurveys: ActiveSurveyItem[] = [
  {
    id: "SRV-2026-01",
    title: "Mid-Semester Midterm Faculty Assessment (Fall 2026)",
    facultyName: "Dr. Rajesh Kumar",
    subject: "DBMS (Database Management Systems)",
    semester: "Semester 5",
    dueDate: "2026-08-10",
    status: "Pending",
    type: "Faculty",
  },
  {
    id: "SRV-2026-02",
    title: "End-Course Evaluation & Practical Lab Audit",
    facultyName: "Prof. Ananya Roy",
    subject: "Operating Systems",
    semester: "Semester 5",
    dueDate: "2026-08-15",
    status: "Pending",
    type: "Course",
  },
  {
    id: "SRV-2026-03",
    title: "Network Security & Protocols Lab Survey",
    facultyName: "Dr. Ravi Shankar",
    subject: "Computer Networks",
    semester: "Semester 5",
    dueDate: "2026-08-20",
    status: "Completed",
    type: "Faculty",
  },
];

export const mockGrievanceCategories: GrievanceCategoryItem[] = [
  { id: "academic", name: "Academic", iconName: "BookOpen", description: "Internal evaluation, attendance discrepancy, revaluation delays", badge: "Academic Office" },
  { id: "examinations", name: "Examinations", iconName: "GraduationCap", description: "Admit card issues, exam schedule clashes, hall ticket errors", badge: "Controller of Exams" },
  { id: "library", name: "Library", iconName: "Library", description: "Fine appeals, digital access issues, missing catalog books", badge: "Central Library" },
  { id: "hostel", name: "Hostel", iconName: "Home", description: "Room maintenance, Wi-Fi connectivity, mess food complaints", badge: "Hostel Warden" },
  { id: "transport", name: "Transport", iconName: "Bus", description: "Bus route delays, pass renewal, seat availability", badge: "Transport Cell" },
  { id: "finance", name: "Finance", iconName: "CreditCard", description: "Fee payment receipts, refund status, portal billing errors", badge: "Accounts Branch" },
  { id: "scholarship", name: "Scholarship", iconName: "Award", description: "Government scheme disbursement, NSP status verification", badge: "Scholarship Cell" },
  { id: "harassment", name: "Harassment", iconName: "ShieldAlert", description: "Strict anti-ragging squad, behavioral conduct, safety issues", badge: "Disciplinary Committee" },
  { id: "technical", name: "Technical", iconName: "Wrench", description: "LMS portal bugs, Wi-Fi authentication, password resets", badge: "IT Support Desk" },
  { id: "other", name: "Other", iconName: "HelpCircle", description: "General campus facilities, cafeteria, security desk feedback", badge: "Student Welfare" },
];

export const mockStudentServices: StudentServiceItem[] = [
  {
    id: "SVC-101",
    title: "Bonafide Certificate",
    description: "Official proof of university enrollment for passports, bank loans, and official visas.",
    category: "Certificates",
    iconName: "FileCheck",
    fee: "Free",
    estimatedDays: "1 Business Day",
    department: "Academic Section",
  },
  {
    id: "SVC-102",
    title: "Study Certificate",
    description: "Attestation letter of active study status for government schemes and competitions.",
    category: "Certificates",
    iconName: "FileText",
    fee: "Free",
    estimatedDays: "1 Business Day",
    department: "Academic Section",
  },
  {
    id: "SVC-103",
    title: "Transcript",
    description: "Official academic grade sheet transcript certified by the Registrar.",
    category: "Academic Records",
    iconName: "GraduationCap",
    fee: "₹250",
    estimatedDays: "3 Business Days",
    department: "Controller of Exams",
  },
  {
    id: "SVC-104",
    title: "Migration Certificate",
    description: "Migration certificate for university transfer or higher education registration.",
    category: "Certificates",
    iconName: "Award",
    fee: "₹150",
    estimatedDays: "2 Business Days",
    department: "Registrar Office",
  },
  {
    id: "SVC-105",
    title: "Transfer Certificate",
    description: "Formal conduct and course completion transfer certificate.",
    category: "Certificates",
    iconName: "ShieldCheck",
    fee: "Free",
    estimatedDays: "2 Business Days",
    department: "Registrar Office",
  },
  {
    id: "SVC-106",
    title: "ID Card Reprint",
    description: "Replacement request for lost, broken, or damaged student RFID smart cards.",
    category: "Student ID",
    iconName: "CreditCard",
    fee: "₹100",
    estimatedDays: "1 Business Day",
    department: "Security Desk",
  },
  {
    id: "SVC-107",
    title: "Bus Pass",
    description: "Campus transport shuttle and city transit bus pass authorization.",
    category: "Transport",
    iconName: "Bus",
    fee: "As per Route",
    estimatedDays: "Same Day",
    department: "Transport Cell",
  },
  {
    id: "SVC-108",
    title: "Hostel Request",
    description: "Hostel room allocation, room shift, or maintenance work request.",
    category: "Hostel",
    iconName: "Home",
    fee: "Free",
    estimatedDays: "2 Business Days",
    department: "Hostel Warden",
  },
  {
    id: "SVC-109",
    title: "Library Clearance",
    description: "No-dues clearance certificate from university central library.",
    category: "Clearance",
    iconName: "Library",
    fee: "Free",
    estimatedDays: "Same Day",
    department: "Central Library",
  },
  {
    id: "SVC-110",
    title: "Scholarship Letter",
    description: "Financial aid, merit award, or fee concession recommendation letter.",
    category: "Financial Aid",
    iconName: "Award",
    fee: "Free",
    estimatedDays: "1 Business Day",
    department: "Scholarship Cell",
  },
];

export const mockGrievancesList: GrievanceRecord[] = [
  {
    id: "GRV-2026-081",
    category: "Academic",
    priority: "High",
    title: "Academic Delay in Revaluation Results for DAA",
    description: "Submitted revaluation request 3 weeks ago for DAA exam. Result is still pending.",
    date: "2026-07-28",
    status: "Under Review",
    department: "Controller of Exams",
  },
  {
    id: "GRV-2026-082",
    category: "Transport",
    priority: "Medium",
    title: "Transport Issue - Route 14 Bus Delay",
    description: "Route 14 bus consistently arrives 25 minutes late at City Junction stop.",
    date: "2026-07-30",
    status: "Resolved",
    department: "Transport Cell",
  },
  {
    id: "GRV-2026-083",
    category: "Hostel",
    priority: "High",
    title: "Hostel Complaint - Block B 3rd Floor Hot Water Supply",
    description: "Solar heater in Block B 3rd floor is non-functional for past 4 days.",
    date: "2026-07-31",
    status: "Committee Assigned",
    department: "Hostel Oversight Committee",
  },
];

export const mockHistoryRecords: HistoryRecord[] = [
  {
    id: "HIST-9001",
    type: "Service Request",
    title: "Bonafide Certificate Request for Passport Application",
    date: "2026-07-31",
    status: "In Progress",
    department: "Academic Section",
    referenceId: "REQ-BON-881",
    details: "Digital copy requested for passport verification.",
  },
  {
    id: "HIST-9002",
    type: "Grievance",
    title: "Academic Delay in Revaluation Results for DAA",
    date: "2026-07-28",
    status: "In Progress",
    department: "Controller of Exams",
    referenceId: "GRV-2026-081",
    details: "Assigned to Academic Appeals Committee.",
  },
  {
    id: "HIST-9003",
    type: "Faculty Feedback",
    title: "Dr. Rajesh Kumar — DBMS (Database Management Systems)",
    date: "2026-07-25",
    status: "Submitted",
    department: "Computer Science",
    referenceId: "FB-8801",
    details: "Rated 5.0 Stars. Excellent query optimization lectures.",
  },
  {
    id: "HIST-9004",
    type: "Service Request",
    title: "Official Academic Transcript (2 Copies)",
    date: "2026-07-22",
    status: "Approved",
    department: "Controller of Exams",
    referenceId: "REQ-TRN-742",
    details: "Dispatched to Registrar desk for physical seal.",
  },
  {
    id: "HIST-9005",
    type: "Grievance",
    title: "Transport Issue - Route 14 Bus Delay",
    date: "2026-07-20",
    status: "Resolved",
    department: "Transport Cell",
    referenceId: "GRV-2026-082",
    details: "Additional backup shuttle deployed on Route 14.",
  },
  {
    id: "HIST-9006",
    type: "Course Feedback",
    title: "CS302 - Operating Systems Lab Evaluation",
    date: "2026-07-15",
    status: "Submitted",
    department: "Computer Science",
    referenceId: "FB-8802",
    details: "Rated 4.8 Stars. Recommended Linux kernel debugging tools.",
  },
  {
    id: "HIST-9007",
    type: "Service Request",
    title: "Library Clearance No-Dues Certificate",
    date: "2026-07-10",
    status: "Resolved",
    department: "Central Library",
    referenceId: "REQ-LIB-512",
    details: "No pending fines or unreturned books found.",
  },
];
