export const DEPARTMENTS = [
  "CSE",
  "ECE",
  "ME",
  "AI&DS",
  "Biotech",
];

export const YEARS = [
  "Year 1",
  "Year 2",
  "Year 3",
  "Year 4",
];

export const FEE_STATUSES = ["Paid", "Pending", "Partial"] as const;

export const STUDENT_STATUSES = ["Active", "Inactive", "Graduated", "Risk"] as const;

export const STUDENT_PERMISSIONS = {
  VIEW_STUDENT: "VIEW_STUDENT",
  CREATE_STUDENT: "CREATE_STUDENT",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
  IMPORT_STUDENTS: "IMPORT_STUDENTS",
  EXPORT_STUDENTS: "EXPORT_STUDENTS",
  PROMOTE_STUDENT: "PROMOTE_STUDENT",
  TRANSFER_STUDENT: "TRANSFER_STUDENT",
  VIEW_DOCUMENTS: "VIEW_DOCUMENTS",
  MANAGE_DOCUMENTS: "MANAGE_DOCUMENTS",
  VIEW_TIMELINE: "VIEW_TIMELINE",
  VIEW_CONNECTIONS: "VIEW_CONNECTIONS",
} as const;
