import {
  StudentExamProfile,
  UpcomingExamItem,
  InternalMarkItem,
  SemesterResultItem,
  AvailableCourseItem,
  RegistrationWorkflowStep,
  ExamRegistrationItem,
  HallTicketRecordItem,
} from "./types";

export const MOCK_EXAM_PROFILE: StudentExamProfile = {
  studentId: "STU-2022-CSE-042",
  rollNumber: "22071A0542",
  name: "Gudipati Chandra",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
  program: "Bachelor of Technology (B.Tech)",
  degree: "B.Tech",
  branch: "CSE",
  section: "CSE-A",
  currentSemester: 5,
  batch: "2022-2026",
  academicYear: "2024-2025",
  cgpa: 8.92,
  sgpa: 9.15,
  creditsEarned: 114,
  totalRequiredCredits: 160,
  activeBacklogs: 0,
  rank: 4,
  totalStudents: 120,
  examCenter: "Main Campus - Academic Block A",
  examSession: "Morning FN (09:30 AM - 12:30 PM)",
  advisorName: "Dr. K. V. Rama Rao",
  registrationDeadline: "Feb 05, 2025",
};

// ---------------------------------------------------------
// 1. ALL 8 SEMESTERS COURSES
// ---------------------------------------------------------
export const MOCK_AVAILABLE_COURSES: AvailableCourseItem[] = [
  // SEMESTER 1 (Year 1)
  {
    id: "c101",
    semester: 1,
    code: "MA101",
    name: "Linear Algebra & Calculus",
    faculty: "Dr. S. K. Sharma",
    credits: 4.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Mon, Wed 09:30 - 11:30 AM",
    room: "Block A - 101",
    prerequisite: "None",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c102",
    semester: 1,
    code: "PH101",
    name: "Engineering Physics",
    faculty: "Dr. P. N. Murthy",
    credits: 3.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Tue, Thu 10:00 - 11:30 AM",
    room: "Block A - 102",
    prerequisite: "None",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c103",
    semester: 1,
    code: "CS101",
    name: "Programming in C",
    faculty: "Prof. A. R. Varma",
    credits: 3.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Mon, Fri 01:30 - 03:00 PM",
    room: "Block A - 201",
    prerequisite: "None",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c104",
    semester: 1,
    code: "CS102",
    name: "Programming Lab",
    faculty: "Prof. A. R. Varma",
    credits: 1.5,
    category: "Lab",
    availableSeats: 0,
    totalSeats: 30,
    timings: "Thu 02:00 - 05:00 PM",
    room: "Lab Block - 01",
    prerequisite: "None",
    isRegistered: true,
    status: "Full",
  },

  // SEMESTER 2 (Year 1)
  {
    id: "c201",
    semester: 2,
    code: "MA201",
    name: "Advanced Calculus & ODE",
    faculty: "Dr. S. K. Sharma",
    credits: 4.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Mon, Wed 09:30 - 11:30 AM",
    room: "Block A - 101",
    prerequisite: "MA101",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c202",
    semester: 2,
    code: "EE201",
    name: "Basic Electrical Engineering",
    faculty: "Dr. R. C. Rao",
    credits: 3.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Tue, Thu 11:30 - 01:00 PM",
    room: "Block B - 204",
    prerequisite: "None",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c203",
    semester: 2,
    code: "CS201",
    name: "Data Structures & Algorithms",
    faculty: "Dr. John Smith",
    credits: 4.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Mon, Thu 01:30 - 03:30 PM",
    room: "Block A - 302",
    prerequisite: "CS101",
    isRegistered: true,
    status: "Full",
  },

  // SEMESTER 3 (Year 2)
  {
    id: "c301",
    semester: 3,
    code: "CS202",
    name: "Discrete Mathematics",
    faculty: "Dr. S. K. Sharma",
    credits: 3.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Mon, Wed 10:00 - 11:30 AM",
    room: "Block A - 202",
    prerequisite: "MA101",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c302",
    semester: 3,
    code: "CS203",
    name: "Object Oriented Programming (Java)",
    faculty: "Kanneganti Suresh",
    credits: 4.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Tue, Fri 09:30 - 11:30 AM",
    room: "Block A - 303",
    prerequisite: "CS101",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c303",
    semester: 3,
    code: "CS204",
    name: "Digital Logic Design",
    faculty: "Thota Pranitha",
    credits: 3.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Wed, Fri 01:30 - 03:00 PM",
    room: "Block B - 105",
    prerequisite: "None",
    isRegistered: true,
    status: "Full",
  },

  // SEMESTER 4 (Year 2)
  {
    id: "c401",
    semester: 4,
    code: "CS205",
    name: "Operating Systems",
    faculty: "Dr. John Smith",
    credits: 4.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Mon, Wed 11:30 - 01:30 PM",
    room: "Block A - 301",
    prerequisite: "CS201",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c402",
    semester: 4,
    code: "CS206",
    name: "Computer Organization & Architecture",
    faculty: "Thota Pranitha",
    credits: 3.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Tue, Thu 02:00 - 03:30 PM",
    room: "Block A - 204",
    prerequisite: "CS204",
    isRegistered: true,
    status: "Full",
  },
  {
    id: "c403",
    semester: 4,
    code: "CS207",
    name: "Formal Languages & Automata Theory",
    faculty: "Dr. S. K. Sharma",
    credits: 3.0,
    category: "Core",
    availableSeats: 0,
    totalSeats: 60,
    timings: "Mon, Fri 09:30 - 11:00 AM",
    room: "Block A - 102",
    prerequisite: "CS202",
    isRegistered: true,
    status: "Full",
  },

  // SEMESTER 5 (Year 3) - CURRENT SEMESTER FROM SCREENSHOT!
  {
    id: "c501",
    semester: 5,
    code: "CS301",
    name: "Computer Networks",
    faculty: "Dr. John Smith",
    credits: 3.0,
    category: "Core",
    availableSeats: 12,
    totalSeats: 60,
    timings: "Mon, Wed 09:30 - 11:00 AM",
    room: "Block A - 301",
    prerequisite: "CS205",
    isRegistered: true,
    status: "Open",
  },
  {
    id: "c502",
    semester: 5,
    code: "CS302",
    name: "Database Management Systems",
    faculty: "Thota Pranitha",
    credits: 4.0,
    category: "Core",
    availableSeats: 8,
    totalSeats: 60,
    timings: "Tue, Thu 11:30 - 01:30 PM",
    room: "Block A - 302",
    prerequisite: "CS201",
    isRegistered: true,
    status: "Open",
  },
  {
    id: "c503",
    semester: 5,
    code: "CS303",
    name: "Advanced Java Programming Lab",
    faculty: "Kanneganti Suresh",
    credits: 1.5,
    category: "Lab",
    availableSeats: 4,
    totalSeats: 30,
    timings: "Thu 02:00 - 05:00 PM",
    room: "Lab Block - 04",
    prerequisite: "CS203",
    isRegistered: true,
    status: "Open",
  },
  {
    id: "c504",
    semester: 5,
    code: "OE311",
    name: "Intellectual Property Rights",
    faculty: "Thota Pranitha",
    credits: 3.0,
    category: "Open Elective",
    availableSeats: 15,
    totalSeats: 60,
    timings: "Fri 09:30 - 12:30 PM",
    room: "Block B - 102",
    prerequisite: "None",
    isRegistered: true,
    status: "Open",
  },

  // SEMESTER 6 (Year 3)
  {
    id: "c601",
    semester: 6,
    code: "CS305",
    name: "Compiler Design",
    faculty: "Dr. John Smith",
    credits: 4.0,
    category: "Core",
    availableSeats: 25,
    totalSeats: 60,
    timings: "Mon, Wed 10:00 - 12:00 PM",
    room: "Block A - 301",
    prerequisite: "CS207",
    isRegistered: false,
    status: "Open",
  },
  {
    id: "c602",
    semester: 6,
    code: "CS306",
    name: "Software Engineering & Agile",
    faculty: "Thota Pranitha",
    credits: 3.0,
    category: "Core",
    availableSeats: 20,
    totalSeats: 60,
    timings: "Tue, Thu 09:30 - 11:00 AM",
    room: "Block A - 304",
    prerequisite: "None",
    isRegistered: false,
    status: "Open",
  },
  {
    id: "c603",
    semester: 6,
    code: "PE321",
    name: "Artificial Intelligence & ML",
    faculty: "Kanneganti Suresh",
    credits: 3.0,
    category: "Professional Elective",
    availableSeats: 10,
    totalSeats: 60,
    timings: "Fri 01:30 - 04:30 PM",
    room: "Block A - 305",
    prerequisite: "CS201",
    isRegistered: false,
    status: "Open",
  },

  // SEMESTER 7 (Year 4)
  {
    id: "c701",
    semester: 7,
    code: "CS401",
    name: "Cloud Computing & DevOps",
    faculty: "Dr. K. V. Rama Rao",
    credits: 3.0,
    category: "Core",
    availableSeats: 30,
    totalSeats: 60,
    timings: "Mon, Wed 01:30 - 03:00 PM",
    room: "Block C - 101",
    prerequisite: "CS301",
    isRegistered: false,
    status: "Open",
  },
  {
    id: "c702",
    semester: 7,
    code: "PE412",
    name: "Cyber Security & Cryptography",
    faculty: "Thota Pranitha",
    credits: 3.0,
    category: "Professional Elective",
    availableSeats: 18,
    totalSeats: 60,
    timings: "Tue, Thu 10:00 - 11:30 AM",
    room: "Block C - 102",
    prerequisite: "CS301",
    isRegistered: false,
    status: "Open",
  },

  // SEMESTER 8 (Year 4)
  {
    id: "c801",
    semester: 8,
    code: "PR401",
    name: "Major Capstone Project & Internship",
    faculty: "Dr. K. V. Rama Rao",
    credits: 12.0,
    category: "Project",
    availableSeats: 60,
    totalSeats: 60,
    timings: "Full Day Industrial Residency",
    room: "Industry / Innovation Center",
    prerequisite: "All Core Credits",
    isRegistered: false,
    status: "Open",
  },
];

// ---------------------------------------------------------
// 2. EXAM REGISTRATIONS FOR ALL SEMESTERS
// ---------------------------------------------------------
export const MOCK_EXAM_REGISTRATIONS: ExamRegistrationItem[] = [
  // Sem 5 (Current)
  {
    id: "er501",
    semester: 5,
    examType: "Regular",
    subjectCode: "CS301",
    subjectName: "Computer Networks",
    credits: 3.0,
    feeAmount: 500,
    lateFee: 0,
    paymentStatus: "Paid",
    registrationDeadline: "Feb 05, 2025",
    examCentrePreference: "Main Campus - Block A",
    status: "Approved",
    receiptNumber: "EXM-REC-9012",
  },
  {
    id: "er502",
    semester: 5,
    examType: "Regular",
    subjectCode: "CS302",
    subjectName: "Database Management Systems",
    credits: 4.0,
    feeAmount: 500,
    lateFee: 0,
    paymentStatus: "Paid",
    registrationDeadline: "Feb 05, 2025",
    examCentrePreference: "Main Campus - Block A",
    status: "Approved",
    receiptNumber: "EXM-REC-9013",
  },
  {
    id: "er503",
    semester: 5,
    examType: "Regular",
    subjectCode: "CS303",
    subjectName: "Advanced Java Programming Lab",
    credits: 1.5,
    feeAmount: 350,
    lateFee: 0,
    paymentStatus: "Paid",
    registrationDeadline: "Feb 05, 2025",
    examCentrePreference: "Main Campus - Lab Block",
    status: "Approved",
    receiptNumber: "EXM-REC-9014",
  },
  {
    id: "er504",
    semester: 5,
    examType: "Regular",
    subjectCode: "OE311",
    subjectName: "Intellectual Property Rights",
    credits: 3.0,
    feeAmount: 500,
    lateFee: 0,
    paymentStatus: "Paid",
    registrationDeadline: "Feb 05, 2025",
    examCentrePreference: "Main Campus - Block B",
    status: "Approved",
    receiptNumber: "EXM-REC-9015",
  },
];

// ---------------------------------------------------------
// 3. UPCOMING EXAMS & SCHEDULES FOR SEMESTERS
// ---------------------------------------------------------
export const MOCK_UPCOMING_EXAMS: UpcomingExamItem[] = [
  {
    id: "ex501",
    semester: 5,
    subjectCode: "CS301",
    subjectName: "Computer Networks",
    examDate: "Feb 10, 2025",
    timeSlot: "09:30 AM - 12:30 PM",
    duration: "3 Hours",
    hallNumber: "Block A - 302",
    seatNumber: "A-42",
    credits: 3.0,
    type: "Theory",
    status: "Scheduled",
  },
  {
    id: "ex502",
    semester: 5,
    subjectCode: "CS302",
    subjectName: "Database Management Systems",
    examDate: "Feb 12, 2025",
    timeSlot: "09:30 AM - 12:30 PM",
    duration: "3 Hours",
    hallNumber: "Block A - 302",
    seatNumber: "A-42",
    credits: 4.0,
    type: "Theory",
    status: "Scheduled",
  },
  {
    id: "ex503",
    semester: 5,
    subjectCode: "CS303",
    subjectName: "Advanced Java Programming Lab",
    examDate: "Feb 14, 2025",
    timeSlot: "01:30 PM - 04:30 PM",
    duration: "3 Hours",
    hallNumber: "Lab Block - 04",
    seatNumber: "L-12",
    credits: 1.5,
    type: "Lab",
    status: "Scheduled",
  },
  {
    id: "ex504",
    semester: 5,
    subjectCode: "OE311",
    subjectName: "Intellectual Property Rights",
    examDate: "Feb 17, 2025",
    timeSlot: "09:30 AM - 12:30 PM",
    duration: "3 Hours",
    hallNumber: "Block B - 102",
    seatNumber: "B-18",
    credits: 3.0,
    type: "Elective",
    status: "Scheduled",
  },
];

// ---------------------------------------------------------
// 4. PREVIOUS RESULTS FOR ALL COMPLETED SEMESTERS (1 to 4)
// ---------------------------------------------------------
export const MOCK_SEMESTER_RESULTS: SemesterResultItem[] = [
  {
    semester: 1,
    academicYear: "2022-2023",
    monthYear: "May 2023",
    creditsAttempted: 22,
    creditsEarned: 22,
    sgpa: 8.65,
    cgpa: 8.65,
    rank: 6,
    resultStatus: "Pass",
    gradeCardUrl: "#",
    subjects: [
      { code: "MA101", name: "Linear Algebra & Calculus", internal: 36, external: 51, total: 87, grade: "A+", credits: 4, status: "Pass" },
      { code: "PH101", name: "Engineering Physics", internal: 34, external: 49, total: 83, grade: "A+", credits: 3, status: "Pass" },
      { code: "CS101", name: "Programming in C", internal: 38, external: 55, total: 93, grade: "O", credits: 3, status: "Pass" },
      { code: "CS102", name: "Programming Lab", internal: 39, external: 57, total: 96, grade: "O", credits: 1.5, status: "Pass" },
    ],
  },
  {
    semester: 2,
    academicYear: "2022-2023",
    monthYear: "Nov 2023",
    creditsAttempted: 22,
    creditsEarned: 22,
    sgpa: 8.80,
    cgpa: 8.72,
    rank: 5,
    resultStatus: "Pass",
    gradeCardUrl: "#",
    subjects: [
      { code: "MA201", name: "Advanced Calculus & ODE", internal: 35, external: 50, total: 85, grade: "A+", credits: 4, status: "Pass" },
      { code: "EE201", name: "Basic Electrical Engineering", internal: 32, external: 48, total: 80, grade: "A", credits: 3, status: "Pass" },
      { code: "CS201", name: "Data Structures & Algorithms", internal: 38, external: 56, total: 94, grade: "O", credits: 4, status: "Pass" },
    ],
  },
  {
    semester: 3,
    academicYear: "2023-2024",
    monthYear: "May 2024",
    creditsAttempted: 24,
    creditsEarned: 24,
    sgpa: 9.05,
    cgpa: 8.83,
    rank: 4,
    resultStatus: "Pass",
    gradeCardUrl: "#",
    subjects: [
      { code: "CS202", name: "Discrete Mathematics", internal: 37, external: 54, total: 91, grade: "O", credits: 3, status: "Pass" },
      { code: "CS203", name: "Object Oriented Programming (Java)", internal: 39, external: 58, total: 97, grade: "O", credits: 4, status: "Pass" },
      { code: "CS204", name: "Digital Logic Design", internal: 34, external: 50, total: 84, grade: "A+", credits: 3, status: "Pass" },
    ],
  },
  {
    semester: 4,
    academicYear: "2023-2024",
    monthYear: "Nov 2024",
    creditsAttempted: 24,
    creditsEarned: 24,
    sgpa: 9.25,
    cgpa: 8.92,
    rank: 4,
    resultStatus: "Pass",
    gradeCardUrl: "#",
    subjects: [
      { code: "CS205", name: "Operating Systems", internal: 38, external: 57, total: 95, grade: "O", credits: 4, status: "Pass" },
      { code: "CS206", name: "Computer Organization & Arch", internal: 36, external: 52, total: 88, grade: "A+", credits: 3, status: "Pass" },
      { code: "CS207", name: "Formal Languages & Automata", internal: 37, external: 55, total: 92, grade: "O", credits: 3, status: "Pass" },
    ],
  },
];

// ---------------------------------------------------------
// 5. PREVIOUS HALL TICKETS HISTORY
// ---------------------------------------------------------
export const MOCK_PAST_HALL_TICKETS: HallTicketRecordItem[] = [
  {
    id: "ht-sem4",
    semester: 4,
    academicYear: "2023-2024",
    examType: "Regular End-Sem",
    hallTicketNumber: "HT-2024-SEM4-0542",
    generatedDate: "Nov 01, 2024",
    examCenter: "Main Campus - Academic Block A",
    status: "Verified & Issued",
    subjects: [
      { id: "s401", semester: 4, subjectCode: "CS205", subjectName: "Operating Systems", examDate: "Nov 12, 2024", timeSlot: "09:30 AM - 12:30 PM", duration: "3 Hours", hallNumber: "Block A - 204", seatNumber: "A-14", credits: 4, type: "Theory", status: "Completed" },
      { id: "s402", semester: 4, subjectCode: "CS206", subjectName: "Computer Organization & Architecture", examDate: "Nov 15, 2024", timeSlot: "09:30 AM - 12:30 PM", duration: "3 Hours", hallNumber: "Block A - 204", seatNumber: "A-14", credits: 3, type: "Theory", status: "Completed" },
    ],
  },
  {
    id: "ht-sem3",
    semester: 3,
    academicYear: "2023-2024",
    examType: "Regular End-Sem",
    hallTicketNumber: "HT-2024-SEM3-0542",
    generatedDate: "May 02, 2024",
    examCenter: "Main Campus - Academic Block A",
    status: "Verified & Issued",
    subjects: [
      { id: "s301", semester: 3, subjectCode: "CS202", subjectName: "Discrete Mathematics", examDate: "May 10, 2024", timeSlot: "09:30 AM - 12:30 PM", duration: "3 Hours", hallNumber: "Block A - 102", seatNumber: "B-22", credits: 3, type: "Theory", status: "Completed" },
    ],
  },
  {
    id: "ht-sem2",
    semester: 2,
    academicYear: "2022-2023",
    examType: "Regular End-Sem",
    hallTicketNumber: "HT-2023-SEM2-0542",
    generatedDate: "Nov 03, 2023",
    examCenter: "Science Block - Hall 301",
    status: "Verified & Issued",
    subjects: [],
  },
  {
    id: "ht-sem1",
    semester: 1,
    academicYear: "2022-2023",
    examType: "Regular End-Sem",
    hallTicketNumber: "HT-2023-SEM1-0542",
    generatedDate: "May 04, 2023",
    examCenter: "Science Block - Hall 301",
    status: "Verified & Issued",
    subjects: [],
  },
];

export const MOCK_REGISTRATION_WORKFLOW: RegistrationWorkflowStep[] = [
  { step: "Student", actor: "Gudipati Chandra (Self)", date: "Jan 10, 2025", status: "Completed" },
  { step: "Advisor", actor: "Dr. K. V. Rama Rao (Faculty Advisor)", date: "Jan 12, 2025", status: "Completed" },
  { step: "HOD", actor: "Dr. M. S. Reddy (Head of Dept)", date: "Jan 14, 2025", status: "Completed" },
  { step: "Approved", actor: "Controller of Examinations", date: "Jan 15, 2025", status: "Completed" },
];
