import {
  Brain,
  BrainCircuit,
  Search,
  Bell,
  Settings,
  Shield,
  FileText,
  User,
  Users,
  AlertTriangle,
  ArrowRight,
  TrendingDown,
  TrendingUp,
  Download,
  Upload,
  Calendar,
  Layers,
  ChevronRight,
  ChevronLeft,
  X,
  Check,
} from "lucide-react";

export const icons = {
  ai: BrainCircuit,
  brain: Brain,
  search: Search,
  bell: Bell,
  settings: Settings,
  shield: Shield,
  report: FileText,
  user: User,
  users: Users,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  trendDown: TrendingDown,
  trendUp: TrendingUp,
  download: Download,
  upload: Upload,
  calendar: Calendar,
  layers: Layers,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  close: X,
  check: Check,
};

export type AppIconType = keyof typeof icons;
export default icons;
