import {
  RoomDetails,
  HostelInfo,
  MessMenu,
  GatePassRecord,
  ComplaintRecord,
  MaintenanceRequest,
  FeeReceipt,
  VisitorRecord,
  HostelNotice,
} from "./types";

export const mockRoomDetails: RoomDetails = {
  roomNumber: "A-305",
  block: "Boys Hostel - Block A",
  floor: "3rd Floor",
  roomType: "Triple Sharing (AC)",
  capacity: 3,
  occupancy: 2,
  hostelSince: "15 Aug 2024",
  expectedCheckout: "31 May 2027",
  status: "Active & Occupied",
  roommates: [
    {
      id: "rm-101",
      name: "Rahul Sharma",
      department: "Computer Science & Engg",
      semester: "Semester 5",
      contact: "+91 98765 43210",
      avatar: "RS",
      rollNo: "24CSE108",
    },
    {
      id: "rm-102",
      name: "Vamsi Krishna",
      department: "Electronics & Comm Engg",
      semester: "Semester 5",
      contact: "+91 98765 43211",
      avatar: "VK",
      rollNo: "24ECE042",
    },
  ],
};

export const mockHostelInfo: HostelInfo = {
  name: "Boys Hostel - Block A",
  address: "EduSuite Pro Campus, Sector 4, Academic City, University Road",
  wardenName: "Dr. S. Ramesh",
  assistantWarden: "Mr. M. Pattnaik",
  officeTiming: "09:00 AM - 06:00 PM (Mon - Sat)",
  emergencyContact: "+91 94444 12345 / 040-27891234",
  amenities: {
    wifi: "High-Speed 100Mbps Fiber Access (24/7)",
    laundry: "Bi-weekly complimentary washing (Tues & Fri)",
    water: "24/7 RO Purified Drinking & Hot Utility Water",
    powerBackup: "100% Dual DG Set Automatic Backup",
    medicalRoom: "In-house 24/7 Nurse Station & First-Aid Desk",
  },
};

export const mockWeeklyMessMenu: MessMenu[] = [
  {
    day: "Monday",
    breakfast: "Idli, Vada, Sambhar, Coconut Chutney, Tea / Coffee",
    lunch: "Paneer Butter Masala, Dal Tadka, Jeera Rice, Chapati, Curd, Salad",
    snacks: "Samosa, Mint Chutney, Hot Tea",
    dinner: "Aloo Gobi, Plain Rice, Mix Dal, Phulka, Gulab Jamun",
  },
  {
    day: "Tuesday",
    breakfast: "Puri Bhaji, Sprouted Moong, Milk / Tea",
    lunch: "Veg Biryani, Mirchi Ka Salan, Raita, Fryums",
    snacks: "Veg Cutlet, Hot Coffee",
    dinner: "Kadhai Paneer, Yellow Dal, Chapati, Kheer",
  },
  {
    day: "Wednesday",
    breakfast: "Masala Dosa, Tomato Chutney, Tea",
    lunch: "Rajma Masala, Steamed Rice, Butter Roti, Boondi Raita",
    snacks: "Bread Pakora, Green Chutney",
    dinner: "Veg Kolhapuri, Dal Makhani, Phulka, Ice Cream",
  },
  {
    day: "Thursday",
    breakfast: "Aloo Paratha, Curd, Pickle, Tea",
    lunch: "Chole Bhature, Veg Pulao, Curd, Salad",
    snacks: "Pav Bhaji, Lemonade",
    dinner: "Mix Veg Curry, Rice, Tomato Rasam, Jalebi",
  },
  {
    day: "Friday",
    breakfast: "Poha, Sev, Upma, Tea / Coffee",
    lunch: "Veg Korma, Sambar Rice, Papad, Curd",
    snacks: "Onion Pakoda, Ginger Tea",
    dinner: "Paneer Tikka Masala, Jeera Rice, Butter Naan, Fruit Salad",
  },
  {
    day: "Saturday",
    breakfast: "Uttapam, Coconut Chutney, Filter Coffee",
    lunch: "Veg Thali (Paneer, Dal, Rice, 3 Rotis, Sweet)",
    snacks: "Biscuit & Tea",
    dinner: "Aloo Matar, Dal Fry, Chapati, Rasgulla",
  },
  {
    day: "Sunday",
    breakfast: "Chole Kulcha, Lassi",
    lunch: "Special Hyderabadi Veg Biryani, Double Ka Meetha, Raita",
    snacks: "Dry Fruits & Milk / Coffee",
    dinner: "Special Paneer Butter Masala, Pulao, Butter Naan, Chocolate Sundae",
  },
];

export const mockGatePasses: GatePassRecord[] = [
  {
    id: "gp-001",
    refId: "GP-2026-8841",
    purpose: "Weekend Home Visit",
    destination: "Hyderabad (Home)",
    outDate: "2026-08-08",
    outTime: "05:00 PM",
    returnDate: "2026-08-10",
    returnTime: "08:00 PM",
    guardianApproval: "Verified via SMS Call (+91 98490 12345)",
    status: "Approved",
    qrCodeUrl: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=GP-2026-8841-A305",
  },
  {
    id: "gp-002",
    refId: "GP-2026-7210",
    purpose: "Local Outing & Books Purchase",
    destination: "City Center Mall",
    outDate: "2026-07-28",
    outTime: "02:00 PM",
    returnDate: "2026-07-28",
    returnTime: "08:30 PM",
    guardianApproval: "Self Approved (Local)",
    status: "Completed",
    qrCodeUrl: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=GP-2026-7210-COMPLETED",
  },
  {
    id: "gp-003",
    refId: "GP-2026-6401",
    purpose: "Medical Consultation",
    destination: "Apollo Hospital",
    outDate: "2026-07-14",
    outTime: "10:00 AM",
    returnDate: "2026-07-14",
    returnTime: "04:00 PM",
    guardianApproval: "Approved by Warden Office",
    status: "Completed",
    qrCodeUrl: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=GP-2026-6401-COMPLETED",
  },
];

export const mockComplaints: ComplaintRecord[] = [
  {
    id: "cmp-001",
    ticketNo: "HST-CMP-409",
    category: "Electricity",
    priority: "High",
    description: "Study table tube light flickering constantly in Room A-305.",
    status: "In Progress",
    assignedStaff: "Electrician Kumar (Ext: 402)",
    dateRaised: "2026-07-31",
  },
  {
    id: "cmp-002",
    ticketNo: "HST-CMP-312",
    category: "Water",
    priority: "Low",
    description: "Washroom tap dripping slowly on 3rd Floor East Wing.",
    status: "Resolved",
    assignedStaff: "Plumber Ramesh",
    dateRaised: "2026-07-20",
    resolutionDate: "2026-07-21",
  },
  {
    id: "cmp-003",
    ticketNo: "HST-CMP-198",
    category: "Internet",
    priority: "Medium",
    description: "Wi-Fi Router Signal low near Room A-305 door.",
    status: "Resolved",
    assignedStaff: "IT Network Desk",
    dateRaised: "2026-07-10",
    resolutionDate: "2026-07-11",
  },
];

export const mockMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: "maint-101",
    reqNo: "MAINT-882",
    item: "Geyser Power Switch Switchboard",
    category: "Electricity",
    status: "In Progress",
    assignedStaff: "Electrician Kumar",
    date: "2026-08-01",
  },
  {
    id: "maint-102",
    reqNo: "MAINT-750",
    item: "Bed 2 Wooden Slat Alignment",
    category: "Furniture",
    status: "Completed",
    assignedStaff: "Carpenter Joseph",
    date: "2026-07-15",
  },
  {
    id: "maint-103",
    reqNo: "MAINT-610",
    item: "AC Filter Cleaning & Servicing",
    category: "HVAC",
    status: "Completed",
    assignedStaff: "Cooling Tech India",
    date: "2026-06-28",
  },
];

export const mockFeeReceipts: FeeReceipt[] = [
  {
    receiptNo: "RCP-HST-2026-001",
    date: "10 Jul 2026",
    amount: "₹22,500",
    term: "Autumn Semester 2026 (Part 1)",
    status: "Paid",
    downloadUrl: "#",
  },
  {
    receiptNo: "RCP-HST-2026-002",
    date: "05 Jan 2026",
    amount: "₹22,500",
    term: "Spring Semester 2026 (Part 2)",
    status: "Paid",
    downloadUrl: "#",
  },
];

export const mockVisitors: VisitorRecord[] = [
  {
    id: "vis-1",
    visitorName: "Ramesh Sharma",
    relationship: "Father",
    date: "2026-07-28",
    inTime: "10:30 AM",
    outTime: "01:15 PM",
    approvedBy: "Warden Office",
    verificationStatus: "Verified",
  },
  {
    id: "vis-2",
    visitorName: "Sunita Sharma",
    relationship: "Mother",
    date: "2026-06-15",
    inTime: "02:00 PM",
    outTime: "05:30 PM",
    approvedBy: "Assistant Warden",
    verificationStatus: "Verified",
  },
];

export const mockHostelNotices: HostelNotice[] = [
  {
    id: "hn-1",
    title: "Overhead Water Tank Cleaning & Sanitization",
    category: "Maintenance",
    date: "Today",
    priority: "High",
    description: "Water supply in Block A & B will be suspended between 06:00 AM and 09:00 AM this Saturday due to tank cleaning.",
  },
  {
    id: "hn-2",
    title: "Independence Day Special Feast Menu Announced",
    category: "Mess",
    date: "Yesterday",
    priority: "Low",
    description: "Special lunch and dinner feast will be served in Central Mess on 15th August. Mess passes not required for resident inmates.",
  },
  {
    id: "hn-3",
    title: "Monthly Warden Room Inspection Drive",
    category: "Inspection",
    date: "3 days ago",
    priority: "Urgent",
    description: "Monthly cleanliness & electrical compliance audit will be conducted by Warden Team on Friday afternoon.",
  },
  {
    id: "hn-4",
    title: "Inter-Block Carrom & Table Tennis League",
    category: "Events",
    date: "4 days ago",
    priority: "Low",
    description: "Registrations open for Inter-Block Indoor Championship at Block A Sports Lounge. Cash prizes and trophies for winners.",
  },
];
